### ISSUE TITLE
Migration to other server.

### ISSUE THREAD

**Issue by azmatullah** [kimai/kimai#1079]
Hi,

I'm moving Kimai to one server to another server. I've changes database configuration successfully but I failed to find url configuration. I'm accessing it on localhost after setting up database, its not accessing.
How to set url setting in KIMAI, ealirer we use name kimai then after moving I'm using folder name 'timetracker'
 Please help,

Thanks,
Azmat

#### Expected behaviour
NA
#### Actual behaviour
NA
#### Steps to reproduce
NA
#### Reproducable on demo.kimai.org? [yes|no]
NA
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
Version 1.1.0

**Comment by mibsk** [comment]
Hello,

so from "kimai.oldserver.pk" to "timetracker.newserver.pk"
OR
"www.oldserver.pk/kimai" to "www.newserver.pk/timetracker"

What about an errors in apache error_log file?

**Comment by reddatos** [comment]
Hi mibsk, I'm trying to do the same thing. I'm migrating from oldserver.com/kimai to newerver.com/kimai, both servers have the same IP address, I'm running Apache2 under Ubuntu 18.04, the oldserver is Ubuntu 16.04.

What I've tried was to migrate the SQL database using phpMyAdmin, it was successfully, but when I tried to login newserver.com/kimai (192.168.1.4/kimai) I was asked to verified the autoconfig file. Then I noticed that since I previously installed kimai in the new server, the autoconfig file was different than the one in the old server.

Should I just migrate the database and then rerun the installer with the database in place?

**Comment by kevinpapst** [comment]
Best is to scp the complete folder from old server to new server (otherwise you might update Kimai without noticing).
Then copy the database and adjust the autoconf (new server) and point to the new database.

**Comment by reddatos** [comment]
That makes sense, thanks for replying so fast and for the great platform you all have created. Very appreciated.

**Comment by reddatos** [comment]
I was able to migrate Kimai to another server, however, for some reason, when an user tries to record an activity the timer starts with "12:00:00" and when the activity stops it shows the minutes recorder from the time right after the migration. What I mean is that the timer is running since the last time Kimai was up.

**Comment by simonschaufi** [comment]
Hello @reddatos your mentioned issue is not reproduceable, therefor you need to do some research by yourself to find out where the problem comes from. My guess is that the server time is not correct or some other time zone issue.
