### ISSUE TITLE
Fails after install

### ISSUE THREAD

**Issue by woolmonkey** [kimai/kimai#1095]
#### Expected behaviour
Should go to login screen
#### Actual behaviour
After install has finished click on install and get an error that the databses already exist.  But they didn't then it want's to updte the databases but fails.  This is with the latest stable release.

**Comment by simonschaufi** [comment]
We made this issue template to fill it out, not to leave it empty. please give us all information

**Comment by donotshake** [comment]
**Expected behavior**
Should present login screen after creating tables during installation. 

**Actual behavior**
Database error, installation restarts.

**Steps to reproduce**
On a freshly deployed Apache/2.4.25 Debian 9 Server with 10.1.26-MariaDB, follow install instructions to browser installation and deploy kimai. 

```
CREATE DATABASE timedb;
CREATE USER 'time'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON timedb.* TO time@localhost;
FLUSH PRIVILEGES;
quit
```
During browser setup, select English > Agree to License > System Requirements are met > timezone> Write-permissions good > enter localhost database login information > select db (I named "timedb") accept default prefix > install > "Error during installation!
Kimai is unable to create necessary tables because tables with the name name already exist.
To update your existing installation please click here.
Choose another table prefix or delete existing tables with this prefix in order to allow Kimai to perform a clean installation. "

Verified tables were created. I had changed the prefix a couple times retrying the installation so there are multiple sets of tables in the timedb

**Reproducible on demo.kimai.org?** no
**Kimai version:** Installation v1.1.0.1389 (Stable)

Relevant log entries from log file (debug tab or temporary/logfile.txt)

**Comment by simonschaufi** [comment]
can you try with the latest master? we fixed something with mariadb.

**Comment by donotshake** [comment]
Installation v1.2.2.1394 Worked. Thank you!
