### ISSUE TITLE
Login not possible after upgrade from 0.9.2 (1306) to 1.1.0 

### ISSUE THREAD

**Issue by hcrisgnya** [kimai/kimai#1097]
Related Issue: #581 

#### Expected behaviour
The upgrade from version 0.9.2 (1306) to 1.1.0  has been passed successfully without issues. 
#### Actual behaviour
Its not possible to login with any of the old users neither with admin and changeme.
#### Steps to reproduce
Run upgrade installation steps:
1. Download new version 1.1.0
2. Backup old KIMAI to KIMAI092
3. Unzip in new version directory KIMAI
4. Adjust permission and ownership (777/www-data)
5. autoconf.php from old installation to new KIMAI
6. Visit KIMAI Url and process the upgrade steps
Result: Login not possible

Second attempt:
New installation to create an autoconf.php. 
Copy and store the autoconf.php. 
Dump the installation and run the upgrade as described above.
Replace the autoconfig.php of the upgraded installation with the old backup but keep the salt-string.

#### Reproducable on demo.kimai.org? [yes|no]
no

#### Kimai version
0.9.2 (1306) to 1.1.0

**Comment by simonschaufi** [comment]
If the salt is still the same, we can't do anything. As you said, the upgrade process went fine. I don't know where the problem should be as we don't touch the login credentials of the users and nothing has changed since 0.9.2

**Comment by frederickjh** [comment]
I am seeing the exact same results in trying to upgrade from 0.9.4 to 1.3.1. I have diffed the `autoconf.php` files and also compared the **kimai_usr** table in the database to the same table in the back up and in both cases they are the same.

Looking through the code I get the feeling that something in this [commit](https://github.com/kimai/kimai/commit/1816514a40a437b57dbdaec051534027b7bfcf1b#diff-828e0013b8f3bc1bb22b4f57172b019d) is causing this but I can't put my finger on exactly what.

**Comment by simonschaufi** [comment]
well, a solution could be to create a php script with the given password and salt, md5 it and then enter this pw into the db field. Then you can login again and change the other user's pws as well.

**Comment by frederickjh** [comment]
I will try this update again in the morning. I did notice that in the new database there were both a kimai_usr table and a kimai_users table. It could be that in the process of updating I started the installer instead. I will document the steps that I do to see what is needed to successfully update.

**Comment by simonschaufi** [comment]
yeah, never run the installer. the installer as it sais is the installer and the updater the updater ;)

**Comment by frederickjh** [comment]
I have my webroot link (`public_html`) to a folder that contains the current version of Kimai. This makes it easy to change between versions if an upgrade fails. Adjust the directions below if your webroot is named something else or you do not use a symlink.

1. Create new folder for new version of Kimai (ie. `public_html-kimai_1.3.1`) and `cd` into it.
2. Download the Kimai zip file of the new version into this folder
3. `unzip kimai_1.3.1.zip`
4. `chmod -R a+w temporary`
5. Copy `includes/autoconfig.php` from the folder containing the old version of Kimai to the folder containing the new version of Kimai into `includes/autoconfig.php`.
5. Note: on my webhosting I also needed to have a .htaccess file with `Options +FollowSymLinks` in it because of my symlinking.
6. Remove or rename the current link named `public_html` and create or rename one that points to the folder containing the new version of Kimai.
7. Go to `<YourDomainName>/updater/updater.php`. You should be given the option to update your database or it will complain if it does not find a configured `includes/autoconfig.php` file.

Not quite as simple as the instructions on the Download page:

![image](https://user-images.githubusercontent.com/864159/44451746-e22cf300-a5f4-11e8-912f-135b918f87fd.png)

Now maybe the installer would have started `updater.php` (I did not take time to look at the code.) if it had seen that I had copied `includes/autoconfig.php` into the new version installation and started the updater, but even to copy `autoconfig.php` to the new installation is not in the instructions. So, when I followed the installer instructions, (Start your browser and go to your Kimai directory.) I managed to botch my install the first time with the installer.

**Comment by frederickjh** [comment]
There really should be instructions like these in an UPDATE.md file in the releases.

**Comment by simonschaufi** [comment]
If you want to help us improve the documentation, we would highly appreciate that!

➡️  https://github.com/kimai/www.kimai.org/tree/master/documentation

**Comment by frederickjh** [comment]
@simonschaufi I am working on updating the documentation. One clarification, Is my step *8.* above correct?
Should they go to  `<YourDomainName>/updater/updater.php`? or should they just go to  `<YourDomainName>` where Kimai is installed?

Will the scripts check if autoconfig.php is not empty and then run the updater.php or does it have to be run directly?

I ran it directly and did not try to see if it would start the updater. I believe that I did not copy autoconfig.php over before visiting `<YourDomainName>`, and then the installer ran.

**Comment by simonschaufi** [comment]
> Is my step 8. above correct?

Just start kimai normally. It will check at every start if the database needs to be migrated. If so, it automatically redirects you to the updater.

You have to make sure the `autoconfig.php` is there (which is the case if you will overwrite kimai completely with the new version).

**Comment by frederickjh** [comment]
Thanks I have created a [pull request](https://github.com/kimai/www.kimai.org/pull/21) with an update to the documentation regarding using the updater.
