### ISSUE TITLE
Migration to openTBS and support for MS Word invoice templates available

### ISSUE THREAD

**Issue by AlxBe** [kimai/kimai#1112]
A working migration to openTBS and MS Word invoice template support can be found here: https://github.com/AlxBe/kimai

Due to my insufficient git knowledge I did not follow the contribute guidelines. Also there might be spaces in the code.

Feel free to implement. 
Regards Alex

**Comment by simonschaufi** [comment]
Thank you very much for your great work!

One more thing and then I would be really happy: Instead of adding the plugin by hand, could you please add it via [composer](https://packagist.org/packages/tinybutstrong/opentbs)?

You can just add it as dependency and composer will take care about the autoloading.

**Comment by AlxBe** [comment]
As I tried to figure out the proper use of git, I recognised, that a branch is aproper way to implement features. As you can't have two forks of the same repository in one account I had to start with a new one.... I will try to merge these two accounts soon. Here we go: https://github.com/AlxBe2/kimai/tree/openTBS-migration
Regards Alex

**Comment by kevinpapst** [comment]
Hi @AlxBe , I will close this issue.

Please open your repo (the link you provided to the branch) and then click "New pull request" next to the branch dropdown. This is the proper way to ask for an integration of your changes, so we can then review them together.
