### ISSUE TITLE
Modify "username" in Export from "Loginname" to "Nickname"

### ISSUE THREAD

**Issue by mwortmann** [kimai/kimai#1230]
#### Expected behaviour
The Export view showes in the field Username the Loginname of the user, but I require the Nickname to see the "Realname" 

is it possible to change by myself ? 

Version of Kimai is v1.3.1.1394

Thanks lot.

**Comment by simonschaufi** [comment]
Sure, you can change anything in the code. You just need to find "Loginname" and replace it like you want.

**Comment by hh-ams** [comment]
I would also like to have a solution for this.

I tried to replace 'username' with 'nickname' in line 53 in extensions/ki_export/templates/scripts/helpers/ExcelExporter.php
because i am usually using excel-export. But this does not work - i am not a php programmer but it seems, that the nickname is not available in this scope.

Maybe it should be replaced generally for export on an upper layer. If you could send me the position of where to replace 'username' with 'nickname', i would be so happy ;-)
