### ISSUE TITLE
https request leads to broken page

### ISSUE THREAD

**Issue by amaze-escape** [kimai/kimai#1314]
#### Expected behaviour
The application should work the with https as well as with http.

#### Actual behaviour
All https requests are redirected to: https://kimai.example.com/nl/homepage which does not exist

#### Steps to reproduce
- Install Kimai2 on apache2 server (ubuntu 18.04 server).
- Make sure everything is running fine.
- Install letsencrypt with certbot (with or without redirect).
- Go to https://kimai.example.com

**Comment by kevinpapst** [comment]
Wrong repository, this is Kimai 1.

This issue belongs in here: https://github.com/kevinpapst/kimai2

But I cal tell your right away that https works exactly the same way than http.
See: https://demo.kimai.org/nl/homepage
This will redirect you to the users configured start screen, here to the timesheet if you are logged in, otherwise to https://demo.kimai.org/nl/login
