### ISSUE TITLE
cannot print or preview invoice

### ISSUE THREAD

**Issue by heeen** [kimai/kimai#1322]
#### Expected behaviour

clicking preview shows row of data for invoice sum
clicking print opens invoice document

#### Actual behaviour
clicking preview reloads page without data row
clicking print opens same page in new tab/window

#### Steps to reproduce
I installed using docker-compose with only minor changes to trusted hosts, mysql password
I added a customer, project and activity and added some timesheet entries.
On my local workstation it works, on my webhost, I cannot print or preview.

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
docker-compose master

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
there doesn't seem to be anything in prod.log related to this

**Comment by heeen** [comment]
The preview button in export also does not show anything, however export to pdf itself is working

**Comment by kevinpapst** [comment]
You are in Kimai 1 repository. Your problem is related to Kimai 2: https://github.com/kevinpapst/kimai2

But as you are using Docker and the preview/invoice/exports are working fine, this is likely a problem that was recently fixed. It has to do with the webserver config inside the docker container.
