### ISSUE TITLE
If the language is "no-bo", creation of new customers isn't possible.

### ISSUE THREAD

**Issue by steinbitglis** [kimai/kimai#1326]
#### Expected behaviour
Creation of new customers should work as normal.

#### Actual behaviour
No panel for creating new customers will show up either in the admin panel, nor the front page.

#### Steps to reproduce
Go to the admin panel
Change the language to no-bo (Norwegian Bokmål)

#### Reproducible on demo.kimai.org? [yes|no]
No (it's Kimai 2)

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.3.2

**Comment by kevinpapst** [comment]
Please create this again in https://github.com/kevinpapst/kimai2/issues

**Comment by simonschaufi** [comment]
@kevinpapst i believe he is talking about Kimai 1 as he mentioned the version

**Comment by kevinpapst** [comment]
Hm...

> No (it's Kimai 2)
 
Now that I read it again ... maybe you are right and I misunderstood the sentence.

**Comment by jimlucas** [comment]
March 21, 2020 7:36 AM, "Fredrik Ludvigsen" <notifications@github.com> wrote:

> Expected behaviour
> Creation of new customers should work as normal.
> 
> Actual behaviour
> No panel for creating new customers will show up either in the admin panel, nor the front page.

Fredrik,

I'm currently using v1.3.1.1394 and when adding a user I must enter the username to be added in the field to the left of the "Add User" button.  If you do not populate the username a javascript warning is thrown.

First, are you populating the username firld?
Second, is your browser possibly blockin JS pop-ups?


> 
> Steps to reproduce
> Go to the admin panel
> Change the language to no-bo (Norwegian Bokmål)
> 
> Reproducible on demo.kimai.org? [yes|no]
> No (it's Kimai 2)
> 
> Kimai version [for example: dev 1.1.0.1389|github master|github develop]
> 1.3.2
> 
> Relevant log entries from log file (debug tab or temporary/logfile.txt)
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
Jim Lucas
CMS Webservices
5414085189

**Comment by jimlucas** [comment]
First, no-bo is not recognized by the Zend Framework (at least the one being included in this version of kimai) as a valid locale.  And the Zend Framework (https://github.com/zendframework/zf1) project was EOL as of 2016-09-28.  So we can't expect any updates from that repo.

Due to the way that the Zend Framework is being called, there is no try / catch in place to catch an error that is being thrown when it is attempting to identify the locale, therefore we need to add a try / catch structure on our side to catch this 'thrown' error and allow the PHP process to continue on.

Also, in the event that an error is thrown, we need to add a second call to Zend_Locale::getTranslationList, without passing the unrecognised locale, to populate the countries list.

**Comment by nwinesett** [comment]
@jimlucas Would your commit on line 130 of floaters.php be the same line to add a default country to show in the list based on on a  user's locale?  It's not too big of an issue since you can start typing the country, but ideally a user's primary country would be the default.

I am a newbie, but I was looking at the getDefault() function on the Zend Framework and wondering if that would be useful in this line to retrieve the default territory of the user's browser, environment, and framework.
