### ISSUE TITLE
Optional 2-Factor-Authentication

### ISSUE THREAD

**Issue by RalfHerzog** [kimai/kimai#197]
**Is your feature request related to a problem? Please describe.**
No, it's an enhancement.

**Describe the solution you'd like**
I am increasingly seeing the use of a 2-Factor-Authentication (2FA). It would be great to generate them optionally for users via QR-Code. Fallback login via some recover-codes (as here on github) might be meaningful.

**Describe alternatives you've considered**
No 2-FA as it is now.

**Additional context**
None

**Comment by kevinpapst** [comment]
Interesting feature request! Thanks for the post, I will read more about the available options in PHP.

**Comment by eljuanchosf** [comment]
Hello @kevinpapst!!

I actually forked the repo and trying to add 2FA via Google Authenticator using https://github.com/scheb/two-factor-bundle, but since I'm new to PHP, Sympfony, FOSUserBundle and Guard... I'm at lost! Would it be possible for you to lend me a hand so I can finish this and send a pull request? It would be amazing if you could. :)

**Comment by kevinpapst** [comment]
If lending an hand doesn't mean I do all the work: yes :-D
Simply open a PR from your incomplete work here and put [WIP] in the title. Then we can discuss all questions there.

**Comment by eljuanchosf** [comment]
Alright, PR #435 was created, but there was a failure in the tests.
In case you want to check is here: https://github.com/kevinpapst/kimai2/pull/435

**Comment by stevenhrabok** [comment]
@kevinpapst I thought to re-ignite this request instead of creating a new one. Was there any reason this fell off the radar? I think any application like Kimai where the login is public facing would need some second factor for authentication. Is it possible to know if there is still some possibility for this feature in the near future?

**Comment by timlegge** [comment]
Hi

It is possible with the SAML ligin support.  As long as your identity
provider does 2FA it works finr

Tested on GSuite and Azure

Tim

**Comment by kevinpapst** [comment]
Having a built-in two factor auth would be great (if it is pluggable).
But I don't have the time right now.

**Comment by natopwns** [comment]
I'm willing to try and work on a plugin for this, but I don't know where I would begin. I see that Nextcloud has a TOTP plugin, so it should be possible? I'm going to study the demo plugin for Kimai. I've never touched PHP in my life, so we'll see how far I can get.

**Comment by kevinpapst** [comment]
Two factor implementation will finally ship with the next major release #2902
