### ISSUE TITLE
Kimai2 android app

### ISSUE THREAD

**Issue by anmol26s** [kimai/kimai#198]
Will the Kimai2 run on the Android app?

**Comment by kevinpapst** [comment]
Probably at a later date, but not this year. I hoped that the new responsive layout would reduce the need for a native app.

We'll keep this topic open to see how many users want it. 
@everyone +1 it if you want it as well

**Comment by hmr-it-jr** [comment]
@kevinpapst what about addind a simple meta tag to let the app appear in fullscreen mode on android phones and get an app like feeling?

`<meta name="mobile-web-app-capable" content="yes">`

more information: https://developer.chrome.com/multidevice/android/installtohomescreen

**Comment by kevinpapst** [comment]
Very interesting information @hmr-it-jr !
I created a dedicated ticket for it: #203

**Comment by tommyms** [comment]
Would it be possible to hook up to Kimai 2 via APIs if I make a time tracker app? For example for import/export?

**Comment by tommyms** [comment]
Sounds good. Will definitely consider it.

**Comment by horlabs** [comment]
Does anyone know how to add a POST-Endpoint? I tried to implement new Endpoints, but I always get "405 Method not allowed" for POST.

**Comment by kevinpapst** [comment]
@horlabs please provide a link to your branch, otherwise I can't help

**Comment by horlabs** [comment]
bin/console debug:router shows a POST route to the endpoint, I tried a lot what I've found with Google etc., but I can't get rid of these error

**Comment by kevinpapst** [comment]
Works for me... posting an empty request to http://127.0.0.1:8000/api/activities
Did you try to execute `bin/console cache:clear` even though that should not be neccessary in `dev`

**Comment by horlabs** [comment]
After clearing the cache it works also for me. Thx

**Comment by geniusupgrader** [comment]
I would like to see an Android App, which utilize Notifications (for example when running a timer)

**Comment by geniusupgrader** [comment]
An Android version would make sense, because then you could track time everywhere and offline as well.

**Comment by hmr-it-jr** [comment]
@kevinpapst I've got a question. Let's assume I create an Android and iOS app for Kimai2 which can track times offline. I think about something like a sync. The user has to enter his API-Key and API-Username and the server url. As soon as he has entered it I try to connect to the api and get all customers, projects, etc. The user now can track offline. As soon as he get's internet again I'll push the offline saved entries to the api - and if i get success response I'll delete them from offline storage. But what happens in case the customer/activity/project got deleted in the meantime?

**Comment by kevinpapst** [comment]
Rare edge case, should not really happen.
You should not sync customers and activities before all offline timesheets were synched or cleared, because you would lose the information what was logged.
For the first version I would simply show a message that the remaining entries could not be synched and that they have to be changed due to the missing customers... 
For the long run I would ask the user for confirmation if the entries should a) be deleted or b) be reassigned, like the delete dialogs in Kimai allow.

**Comment by hmr-it-jr** [comment]
@anmol26s @geniusupgrader @horlabs any thought's about first preview of the app?

workflow will be like this:

- install app
- enter api-url, api-username, api-password
- download all customers, etc. and make them offline available
- track times offline
- once there is Internet again sync them with the server/api
- when I sync the offline saved activities I sync the customers, etc., too

![SVID_20190322_234048_1](https://user-images.githubusercontent.com/36242595/54857032-8c8d0600-4cfd-11e9-8c93-540dec53afb9.gif)

**Comment by kevinpapst** [comment]
Very cool!
But ... is there a specific reason why its called "offline tracker"? Being able to store entries offline is a super cool feature, but why not syncing directly if possible?

**Comment by geniusupgrader** [comment]
@hmr-it-jr  Is there a link to a repo? What are your plans on a license (open source?).

**Comment by hmr-it-jr** [comment]
@kevinpapst of course I can ping the api. If it's available I'll push it directly there - if not, I'll save it offline. I've installed Kimai 1 for some agricultural service supplier agencies and since the German mobile network really sucks on the country side having an offline app will help them a lot. I have some worries that the ping request itself will be ok with edge connection on the smartphone but uploading the actual time/s will fail because of slow internet and/or php_max_runtime. So best thing is to make it configurable: try to upload immidiately or manual upload mode.

@geniusupgrader I'll use my company's apple & google developer account to publish the app in the stores. I thought about charging the users the minimum app price and donating this to the kimai2 core project that @kevinpapst continues with developing this great tool. There is no github repo yet.

**Comment by hmr-it-jr** [comment]
any feature requests?

![ezgif-2-160af2fc7107](https://user-images.githubusercontent.com/36242595/54868303-7463c800-4d8b-11e9-93a3-fe686ccafca1.gif)

**Comment by kevinpapst** [comment]
Looks promising 👍 
Just from what I saw in the gif: directly open the project selection after selecting the customer?!

Other Apart from that::
- You can use the official logo if you want 
- Rename it if you upload it to the official stores, something like: "xxx for Kimai 2". I am not sure if there will ever be an "official" app by Kimai, but if I'd like to prevent name collisions.
- An iOS version for me 😈 
- Can you drop me an email at kevin ... kevinpapst.de?

And let me know if you need further API functions for other apps.

**Comment by geniusupgrader** [comment]
Two wishes:
- add possibility to show notifications while tracking time and control the time tracking with notification actions (https://developer.android.com/guide/topics/ui/notifiers/notifications#Actions)
- add possibility to set a reminder to remind you to cancel the time tracking at a specified time interval.

**Comment by hmr-it-jr** [comment]
I think first release will be without this feature, but as soon as I have time to implement it I'll implement it. First tests work:

![Screenshot_20190401_224844_de hmrit kimai2app](https://user-images.githubusercontent.com/36242595/55359002-15abf600-54d1-11e9-9672-6f1c0bbf1cad.jpg)

**Comment by hmr-it-jr** [comment]
@anmol26s @geniusupgrader 

the first version is now available in the Google Play Store: [https://play.google.com/store/apps/details?id=de.hmrit.kimai2app](https://play.google.com/store/apps/details?id=de.hmrit.kimai2app) - ios coming soon.

**Comment by geniusupgrader** [comment]
Bought!
Is this comment of yours still valid?

> I thought about charging the users the minimum app price and donating this to the kimai2 core project that @kevinpapst continues with developing this great tool. There is no github repo yet.

**Comment by hmr-it-jr** [comment]
> Is this comment of yours still valid?

Sure! I already wrote some mails with Kevin about funding some nice plugins for holiday planning, etc.

--------

Let's see how many people decide to buy it. So far only you and two of my employees bought it 😄 

I think lot's of small companies like carpenters, painters and so on would love to use Kimai 2 but they don't know how to set up Kimai 2 which is needed by the app. This might change when Kevin is releasing his hosted cloud version. Then it'd be even possible to preconfigure the app the for the cloud version.

------

Main goal of this app is to track times offline with your smartphone. It's not going to be a clone of the web-version.

**Comment by buzter** [comment]
Looks promising. I'm waiting for iOS-version now-  wich I'll buy for sure!

**Comment by kevinpapst** [comment]
@hmr-it-jr What about [adding the apps to the marketplace](https://www.kimai.org/documentation/store.html)?

**Comment by geniusupgrader** [comment]
Waiting for the notification feature of the app :)
After testing the app for the first few times I have to note two things:
- wasn't aware that you first need to set up an api password. It would be nice if the settings page would've explained that...
- after a fresh install of kimai, you cannot record times immediately, you need to set up a project and activity first. And..., if I remember correctly, you need to make at least one time record in the web, otherwise the app doesn't let you do time recordings.

**Comment by kevinpapst** [comment]
@hmr-it-jr big thanks for your contribution!!!!! I am waiting for the iOS app as well 😁 

But: I'd like to close this issue, as the app is now released. If you want to open some kind of support channel, you could update the [Android app marketplace page](https://www.kimai.org/store/hmr-it-android-offline-tracker.html).

**Comment by hmr-it-jr** [comment]
@geniusupgrader and all other users: you can add feature requests / bug reports here:

https://github.com/hmr-it/kimai2-offline-tracker-app/issues

**Comment by hmr-it-jr** [comment]
@buzter iOS is available now: https://apps.apple.com/de/app/kimai-2-offline-zeiterfassung/id1459757165

**Comment by buzter** [comment]
👍 Already bought. Testing it from starting next week...
