### ISSUE TITLE
PHP Fatal Error: Allowed memory size

### ISSUE THREAD

**Issue by aebner** [kimai/kimai#229]
I followed the installation guide for kimai2 on an virtual machine with:
- CentOS 7
- Apache 2.4.6
- PHP 7.2.7

but at the end I get the following error in 
[Sun Jul 22 20:27:03.420528 2018] [php7:error] [pid 3916] [client 192.168.122.1:42726] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/kimai2/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
[Sun Jul 22 20:27:03.420762 2018] [php7:error] [pid 3916] [client 192.168.122.1:42726] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/kimai2/vendor/symfony/debug/ErrorHandler.php on line 59

What is my failure?
Thanks a lot.

**Comment by kevinpapst** [comment]
Probably wrong file permissions? 
Maybe the logger is trying to write the log file and that fails due to new file permissions, which again results in an error which is trying to be written ... and so on.

Check if there is file in the directory `var/log/` probably called `prod.log`.
If the file exists: post its content here?
If there is no file, set proper missions for /var/log/ so the web server can write the file - try 777 if you are unsure.
