### ISSUE TITLE
Feature request - Calculation of overtime for half and full time epmployees

### ISSUE THREAD

**Issue by eporsche** [kimai/kimai#240]
**Is your feature request related to a problem? Please describe.**
Currently it is possible to track the times of employees spend on projects with budgets. This is good for tracking time and budget on projects. 
However it should also be possible to track the time budget of each employee based on his contract. 
An employee might have a full or half-time contract leading to over time - if he works longer than expected or at weekends.  The amount of over time of each month should accumulate over time.

**Describe the solution you'd like**
Ability to enter planned working time per employee (not per project)
* time calculation model: monthly, yearly, accumulated
* support for full time (planned working time 100% per week) / half time employees (planned working time 50% per week) or pay per hour workers (0% planned per week)

**Comment by therges** [comment]
Please. I really want that!

**Comment by kevinpapst** [comment]
Kimai is primarily a project time tracking solution. It might be extended to care about employee work time tracking in the future, but for now it isn't. Therefor all ideas in this topic area will be closed.

**Comment by urinal-cake** [comment]
@kevinpapst Feel free to close this, if you feel like it still does not apply. My company is willing to sponsor development of Overtime functionality, as it fits best to our needs.

Our business model operates on billing our customers based on hourly and monthly rates. When billing hourly, we also bill for time spent over 40 during the work week (standard U.S. workweek of Monday to Friday, start of week is Sunday.) Therefore, when we bill our clients for work, we send one invoice per project, with line items for each week, and an addition line item if there was overtime.

Every time invoices are sent, timesheets must be exported to excel, and an excel formula added to calculate the week number of the month (typically 1 through 5.) Then, the week from Sunday to Saturday (in the cases of employees working on weekends,) is summed. If it is greater than 40, then we bill time and a half, or two-time.

Initially, I would love to see hours reported throughout the week be tracked against overtime. If an entry brings the employee's hours for the workweek over a set amount of hours (customizable in admin options,) then that time entry may change a different color or have some visual effect. Most importantly, any time in that time entry entry over that set amount of hours, will be calculated at 1.5x or 2x (customizable in admin) the normal hourly rate. This will be reflected in reports.

For this, I see difficulty coming in when having single entries that bring the person's hours _up_ to _and_ over 40 hours. In this case, I would recommend that the system automatically modify the entered time entry to be stored _minus_ the overtime, then have the system create a new entry with the time that was subtracted, and at the new rate. Otherwise, another common issue we deal with when running these calculations, is that since we conduct OT weekly, we need to calculate cross-month overtime. There's also cross-project, and cross-project AND cross-month overtime, but that's too much of a worry I think right now.

We'll just be happy, and be able to improve our efficiency and time spent on invoicing, if these calculations can be done for us, and have reports updated (including PDF reports.) We consistently have to explain to clients why timesheet exports and report money amounts don't match the invoice.

If there are estimates for the amount of time this would take, and the amount of money to complete this work, I would love to hear them.

**Comment by kevinpapst** [comment]
@urinal-cake posting this in a closed issue is definitely the wrong place 😁 

I may consider having a simple setting for users like "weekly working hours" which can then be used to compare times in reports. But most of what you wrote sounds like a solution tailored to your workflow. So I doubt that logic for it should go into Kimai core.

Probably it is better to discuss that via email.

**Comment by kevinpapst** [comment]
There is a new **Working hours, vacation, illness (controlling)** plugin available at: 
https://www.kimai.org/store/controlling.html
