### ISSUE TITLE
Feature request - Ability to book times absent

### ISSUE THREAD

**Issue by eporsche** [kimai/kimai#241]
**Is your feature request related to a problem? Please describe.**
Currently it is possible to track the time spend on projects. However in order to get a complete picture of how the time is spend times absent need also be tracked. 
With this information reports like employer health status and over time ratio are possible. 

**Describe the solution you'd like**
Ability to book absence times
* due to overtime
* illness
* vacation

**Comment by hmr-it-jr** [comment]
In Kimai 1 we've done this with adding a customer "not in office" and projects like "vacation" and "due to overtime" and and activity "away". The good thing is, the employees work time at the end of the month is the same like if he'd worked. So for a vacation day add 8h with the above mentioned customer, project, and activity.

**Comment by nabbisen** [comment]
I add my small opinion.
I would say it's convenient if I could record directly lunch time or time to leave office temporarily for private business which was not summed up.
For example, How about allowing to record minus time with showing warnings? Maybe it also could be to add a field "off work from/to".

**Comment by kevinpapst** [comment]
Yes, you are all correct and something like this is planned, as it is a must-have for most companies.

I can quickly summarize what I have in mind:
- timesheet get a `type` identifying what they are
- a type can be something like `work`, `vacation`, `lunch break`, `sickness`
- a type can have a different form to fill in the values
  - e.g. a holiday might have only a description and from and to date
- a type can either be billable or not
- a type either counts as working time or not
- a type allows parallel tasks or not 

Just that you get a rough idea and leave input. 
Please don't ask for any time estimation, this is a major refactoring task ... but it will come sooner than later.

**Comment by hmr-it-jr** [comment]
There should be a type "(national) holiday" (christmas, new year, etc.). Because the employee get's a full paid day, even if he didn't work and these days are not reducing his vacation days. If the employee tracks this time per week and there was a national holiday on wednesday and there is no time booked on wednesday the time per week of this weeks is not correct.

A feature suggestion: sync the holidays with a calender and add the times to users

**Comment by nabbisen** [comment]
@kevinpapst 
Great. Thanks 🙂

> a type allows parallel tasks or not

Excuse me. If they are parallel, what happens if:

- work: 10:00-18:00 (total 8.0h)
- break (not billable): 12:30-13:30 (total 1.0h)

I mean this way is easier than 😅 :

- work: 10:00-**12:30** (total 2.5h)
- break (not billable): **12:30**-**13:30** (total 1.0h)
- work: **13:30**-18:00 (total 4.5h)

In the latter way, the pairs of bold times have to be linked to each other.

**Comment by kevinpapst** [comment]
I am not sure if I understand the question completely. But a break (or a vacation) would not allow parallel tasks.
But lets assume they would: then your first example is technically valid, but invalid from a business perspective. Kimai can't do anything against it and would calculate 8 hours for that day. 
The second booking would be the right now and Kimai will help you with that => in the future. 
But thats another topic, as pausing/breaks won't be (fully) covered by this request here.

**Comment by nabbisen** [comment]
@kevinpapst 

> would calculate 8 hours for that day.

It answered my question completely 😀

> Kimai will help you with that => in the future

Super great 😆
We sometimes make a mistake such as "10:00-12:00 / 12:30-13:30" (Where has 12:00-12:30 gone?) ... 🙂

Well, yes, that's another topics.

Thanks a lot for all !!

**Comment by Recoil1980** [comment]
Currently I have a separate Customer/Project/Activity all named "OFF" that I have been testing out.  If an employee takes off a day during the week I use the Description to note the reason (i.e. Sick, Dr. Appt., Lazy and should be fired...), which displays on the timesheets for the employee, and boss, to see.

**Comment by hmr-it-jr** [comment]
I've released a plugin which does this job: https://www.kimai.org/store/hmr-it-vacation-bundle.html

**Comment by kevinpapst** [comment]
Kimai is primarily a project time tracking solution. It might be extended to care about employee work time tracking in the future, but for now it isn't. Therefor all ideas in this topic area will be closed.

**Comment by kevinpapst** [comment]
There is a new **Working hours, vacation, illness (controlling)** plugin available at: 
https://www.kimai.org/store/controlling.html
