### ISSUE TITLE
Feature request - highlight national holidays and weekends in calendar view

### ISSUE THREAD

**Issue by eporsche** [kimai/kimai#243]
**Is your feature request related to a problem? Please describe.**
Per employee a country and state should be assigned. Once this is done he is able to see his national holidays in the calendar view. Furthermore weekends can also be distinguished by color in calendar view.
If this feature gets implemented - the employee will be able to see when it is clever to ask for a day off.
Furthermore he can see when he has worked on weekends and holidays - maybe in a later stage - it will also be possible to calculate working hours on such days differently.

**Describe the solution you'd like**
* ability to see national holidays in the calendar view
* ability to distinguish weekends from the rest of the week

**Comment by mr-jingles** [comment]
@kevinpapst ..sorry! I didn't see the new configuration options. 

However I think it would be better to assign holiday calendars to a state rather than to a company/kimai installation. Holidays depend on the state can be quite different from state to state in one country.
Sales Employees for example might work in a different state compared to the state of the headquarter of the company. Relevant for those employees are the holidays in the state they work in.

Employees should therefore be assigned to a state they work / live in and will only see the holidays which will be relevant to them. In a later stage - this would make it possible to calculate the target working hours and overtime for one month based on the employees contract (e.g. full time or half time (50%)) worker.

**Comment by kevinpapst** [comment]
Cleaning up old feature requests which did not get any votes: closing

**Comment by kevinpapst** [comment]
There is a new **Working hours, vacation, illness (controlling)** plugin available at: 
https://www.kimai.org/store/controlling.html

It also cares about public holidays and has calendar integration.
