### ISSUE TITLE
wrong database entry breaks counting

### ISSUE THREAD

**Issue by webzunft** [kimai/kimai#312]
kimai recently had an issue where the end time was not tracked, but the tracking already finished. Technically in table zef the row zef_out was 0. I wasn’t able to neither clear nor finish the tracking in the frontend. Tracking was still possible, but since than no event was finished when I simple pushed the end button but was still running in the background until the next was started. This led to tracking overnight, etc. I just needed to remove the row with the zef_out=0 and it now works again.
I don’t know what caused the initial issue and never had it again, but maybe kimai should validate events somehow to now break when one tracked event is somehow broken.

**Comment by webzunft** [comment]
It happened again and now I have a suspicion.
I clicked twice on the start button, because it didn’t work right away. This was probably due to some slow javascript and so the same tracking got started twice. I could finish one, but not the second and had to remove it manually again.

Just a hunch from my own projects: maybe the ajax call was only partially finished

Hope this helps.

**Comment by kevinpapst** [comment]
Hey guys, this issue is open for a very long time now.
I tried for a couple of hours now to reproduce the problem, by manipulating the database entries to very strange values (which should not be possible to achieve via the regular frontend).

Yes, Kimai did not react completely "normal", but I was able to stop all running tasks one after another, no matter which order I choose to stop them. I could both, stop the ones in the middle, at the beginning and end of the timesheet.

I know, that we refactored the frontend javascript quite a bit. In the past, we did not send the ID of the running task, but only a "stop running task" event, which failed when there were more than one running entry. Today in the same scenario (if you have multiple running entries) you might have to click the stop buzzer multiple times, but it will bring you back to a valid state.

If will close this issue, but if you ever experience such a problem again, please reopen the issue. And even greater: include a database dump that lets me reproduce the problem. In my opinion this problem should not happen again ... but you never know.
