### ISSUE TITLE
Hosting with Softaculous

### ISSUE THREAD

**Issue by freecicero** [kimai/kimai#318]
**Is your feature request related to a problem? Please describe.**

I am a lawyer and currently a user of Time59 for time tracking.  I just came across your program and really like it, and I want to follow along as it progresses.  I particularly like the "spreadsheet-like" format for time entry, with the ability to add a long detailed description.  What I am really looking for is something that lets me select a case and then scroll through all my activity on one screen, seeing what I have done in detail, making changes as needed, and using the resulting screen as sort of a "case manager" to keep me up to date on where I am.  I realize that is not really the design paradigm of the program but it's an obvious use from the way you have set it up.  It's amazingly hard to find a FOSS database-style program that let's you keep a journal of all work and then view it by "case" or "matter" (depending on the term you like to use for a particular "project").

I am on a shared host and don't have the technical ability to set up a instance even for test purposes, so I am looking for a way to bookmark and follow along with your progress in developing the program.  Do you not have any kind of user forum or other update / feedback mechanism other than github?  I see your comments that you are not using the blog very much.  

You have a great and promising design and although I am not a programmer I would like to help in any way possible.  If you need any user feedback beyond what you are already getting please let me know how that can be done.

**Comment by kevinpapst** [comment]
Hey Nathan, thanks for your feedback and input. 

Well, yes you are right - communication is a problem ... like in many open-source projects. I guess developers tend to think their work speaks for themselves ;-) I always plan on write more blog entries and then I sit down and work on another feature, I guess that will likely not change. But I can try.

Its possible to follow the releases with an RSS feed: https://github.com/kevinpapst/kimai2/releases.atom
Thats for now the only other option to follow the progress besides visiting GitHub. And you can always use the demo and check out the progress for yourself. You already found the link I guess?

What would be really helpful: If you could create a mockup of your idea, because I am quite sure that the idea you have in mind is different from what I visualize when I read your post. There are a lot or platforms out there that allow to create and share mockups, but some simple images are fine as well. 

If you create an Issue here please make sure that it has an appropriate title, so more users can find and vote on it. If more people like the idea its more likely that I will add it!

**Comment by nathan2423** [comment]
Thanks for your prompt reply Kevin.  I think I can summarize this way: 

I have been a lawyer for 30+ years billing by the hour, in most cases entering my own time.  The constant frustration of my existence is that the billing time system is very close to being able to fill my needs to make records of the details of the events for which I am billing, but the bill description generally needs to be a summary, while the notes are more detailed.  I don't want to use TWO systems, one for time, and one for "journaling" or "note-keeping" - I have always wanted to use only one.  I've ended up using Ecco Pro or other note-keeping applications, but I've always been frustrated that I end up entering much information twice.  

The developer of the program I am using now is great, and he has added a second "notes" field.  The first one is the description used on the bill, and the second one provides a place to enter more detailed notes that won't show up on the bill.  But because this second field is not implemented on the main "spreadsheet" view of the time entries, it isn't practical to use it.  I need it to show up on the main listing of time entries so that I can scroll through the list of entries and see not only what I billed, but exactly what I did at that entry time.  I don't need rich text, I don't need pictures, I don't need anything but a wrapping display that keeps the narrative of what was done in the same line as the time entry.  

That's what struck me about your current main "time entry" screen.  It's an attractive database format that let's you scroll down the page of your time entries, and see the description of what was done for each entry.  I could see myself easily keeping that screen loaded on my desktop computer, and set the filter for a particular case, and I would then have a scrolling database of every important event that I've done on the case.

I would not ask for additional bells and whistles like places for witnesses or exhibits or other things that would be more appropriate to a "database" format.  That might or might not be something to think about later, but would not be essential to the basic task of being an activity tracker that would let the timekeeper review what was done on the case in one place.

That's the basic idea. Thanks for your interest!

**Comment by nathan2423** [comment]
Oh I meant to add.  My shared host uses Softaculous, which is where I learned about your program, but it has the old version.  I may take a stab at your install instructions, but is there any chance that Softaculous will get the latest version anytime soon?

**Comment by kevinpapst** [comment]
Depending of what you think is "soon" ;-)
They were already asked by another user and replied that they are going to add it, as soon as I release a "stable" version. I guess that could happen until the end of the year. 
Probably you ask them as well, I am sure that its better if they hear the question multiple times.

**Comment by nathan2423** [comment]
Thank you and I will send an email to Softaculous now!

One more comment with visual example.  The ability to have a scrolling list that contains not only the time entry and description but also a more detailed note about the entry is similar to the attractiveness of a program such as www.cintanotes.com  If you refer to the main screenshot on that page, you see on the right side a scrolling list of paragraph-format text notes that are essentially equivalent to time entries.  Although this looks a little like the many two-pane outliners that are on the market, you can see that the right pane is a series of paragaphs that, as you scroll through them, become an "activity log" for whatever case is selected in the filter at the particular moment.  This is much different than the two-pane outline approach where the right side of the screen is always only one "pane" of text, and it is not possible to see at a glance a running list of paragraphs.  I think you can see that your spreadsheet entry format already approximates this Cintanotes format, and the only thing really lacking is the ability to have both a box for the bill description plus a separate box for a longer narrative.

Thanks for your consideration!

**Comment by nathan2423** [comment]
I posted a Softaculous request here:  https://www.softaculous.com/board/index.php?tid=14507

**Comment by nathan2423** [comment]
Well Softaculous has the virtue of consistency.  They told me exactly the same thing:


Group: Softaculous TeamPost Group: Super MemberPosts: 4011Status: | Hi, I just checked the v2 of Kimai and it still not production ready and is missing some of the important features that are present in v1. It is mentioned in their v2 announcement here : https://www.kimai.org/blog/2018/kimai-v2-announcement/ Once they release a stable v2 we will update it in Softaculous asap.
-- | --

**Comment by kevinpapst** [comment]
I don't really understand this, as it is a completely different application, but fair enough.
Thanks for your feedback!

**Comment by softaculous** [comment]
Hi,

I am from the Softaculous team

As mentioned in their announcement about V2 it is not "Production ready" yet :
But we will very likely not call it “production ready” 

Once the latest version is production ready we will update it in Softaculous. 

We are not waiting for the migration script. If V2 is production ready and does not have a migration script from V1 we will still update it as a standalone version without migration from V1

**Comment by kevinpapst** [comment]
Hi @softaculous and @nathan2423 

I released v1.0 of Kimai 2 today. 
Please let me know if I can help in any way to get Kimai on Softaculous.

**Comment by kevinpapst** [comment]
Posted an answer in the board/forum and waiting for feedback now. Closing here
