### ISSUE TITLE
Time is wrong when starting a new activity

### ISSUE THREAD

**Issue by agustaf9** [kimai/kimai#336]
**Describe the bug**
After installing the the time was off by an hour when starting a new activity (the autofilled start and stop time)

I ran `dpkg-reconfigure tzdata` and set the timezone to the correct one (America/Denver) now the autofilled time is ahead by 6 hours.

Changing the customers timezone does not change anything.

**To Reproduce**
1.Setup Kimai2 following installation instructions
2. Reconfigure timezone
3. Start a new activity
4. Autofilled time is wrong

**Expected behavior**
The time that is autofilled should be correct for my timezone

**Desktop (please complete the following information):**
 - OS: Ubunutu 18.04
 - Browser: Firefox

**Comment by kevinpapst** [comment]
For now, Kimai uses server time. If you want to use Kimai in different timezones, there is no support that by now.
As workaround you could try to patch Kimai in order to use your timezone e.g. edit `public/index.php` and add a line like this (see https://secure.php.net/manual/en/timezones.php):
```php
date_default_timezone_set('America/Los_Angeles');
```
Other idea is to change the PHP ini setting for `date.timezone`. This could be done by using your own PHP-FPM pool or probably even simpler with a variable in that vhost.

**Comment by kevinpapst** [comment]
Cool, thanks for the feedback!
I'll re-open the issue, as Kimai should be able to handle that properly out-of-the-box.

**Comment by kevinpapst** [comment]
I need test support with the branch #372 - so if anyone is reading this and as the same error, please give it a try and let me know in #372 if it works.
