### ISSUE TITLE
Feature request: no need to have a client

### ISSUE THREAD

**Issue by andres99** [kimai/kimai#345]
Now, as of Kimai 0.9.2 and 0.9.3 beta 1504, the user cannot add a project without having a client. However, having a client is not always necessary in life. The user should have more freedom and have the option to ignore clients and the clients list altogether. In other words, have an empty clients list and still add projects/activities (which, in that case, are not attributed to any clients).

**Comment by laplix** [comment]
Right now, I find the client field every useful, Since Kimai does not support sub-projects, I use this field as a master project. All sub-project use this master project as their client. The master project is associated to the client, currently my company. But it could be « me ».

I intend to ask for a master -> sub-project feature, recursive.

**Comment by piflixe** [comment]
Hi there,

I think it is very usefull that there must be a client. Otherwise one 
could create a project without specifying someone who pays for it. I 
agree to and support earlier posts that define workarounds:
- no client, no project -> You are the client
- client field can be hidden so overhead is minimal and only when 
creating a new project

regards,
Felix

Felix Piela
August & Piela Konstruktiv GbR
Tempelhofer Weg 11-12
10829 Berlin
Tel. 030 9190 5511
mobil 01523 193 7441
Fax 030 9190 973
www.konstruktiv-berlin.de

Am 03.07.2015 um 02:26 schrieb Louis Lapointe:

**Comment by simonschaufi** [comment]
if I understand you right, you want to have an overview over your own time, or?
kimai is no time tracking system for check in and check out in companies. for that usecase you need to use another software for example: https://github.com/itmastergmbh/SmallTime (http://www.small.li/) but I don't know if that software is also available in english
