### ISSUE TITLE
Clock in/out use?

### ISSUE THREAD

**Issue by Ark74** [kimai/kimai#357]
This is mostly a question about usage.

Has kimai2 been used on clock in / out environments?
Is there any support for fingerprint scanners or other scanners?
Is there any documented use case around?

Thanks for your attention and insides on the matter.
Cheers!

**Comment by kevinpapst** [comment]
Hi @Ark74 , considering the ago of Kimai 2 the answer is: nope ;-)
There is no API yet for starting and stopping entries, in just in development, see #332.
But there is this thread: #315 
So we need some more time before we can set this up properly.
If you have any input, please share it, so it can be taken into account while I work on the API!

**Comment by Ark74** [comment]
Thanks for the answer.

**Comment by rarvin** [comment]
This feature can really help, more like if Kimai has an android or ios app and kimai has a inbuilt bar code scanner then from the bar code it can identify the associated user and a clock in can be done when users are coming over to the office and similarly when the leave office the same can be done and this would be clock out. Something like this would be nice along with a possibility of pulling out a report to see the duration the user has been in office etc. Since this would be like start a task end a task immediatly no time should get added to a user timesheet allowing the user to track time normally too. Same operation can happen for a check out from office and when they do a checkout all tasks that are active for the user could be stopped or left to continue (having this configurable could help).

**Comment by kevinpapst** [comment]
The API has matured a lot since my answer, so all the methods are in place to built that by yourself. 
Kimai will get a clock-in / clock-out mode in the future, as this is necessary for many companies.

**Comment by rarvin** [comment]
Can a log in log off module be adding one in addition to the existing timer. This would be just to indicate attendance and when they are checking into office or work and when they are checking our of office or work. Having this as a separate module within Kimai can really help. And later linking this to stopping all timers when they check out of office would be great.

**Comment by kevinpapst** [comment]
Closing this as I added #829 (explicit issue about hardware support).
@rarvin Please don't misuse issues for completely different topics
