### ISSUE TITLE
Make settings more accessible

### ISSUE THREAD

**Issue by robinrosenstock** [kimai/kimai#365]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to go to the settings. Because the settings are not under "Settings" they are under "User". So the preferences page is a bit hidden. I understand that the options are for the user, but its not very intuitive to click/edit the user to access the settings.

**Describe the solution you'd like**
A clear and concise menu entry for accessing the settings, either on the left OR the right. But not with clicking on the User first.

**Describe alternatives you've considered**
Maybe split the User and the Preferences somehow?

**Additional context**
Coming from #359.

**Comment by kevinpapst** [comment]
Added pull request #369 - do you want to have a look and give me some feedback?

**Comment by geniusupgrader** [comment]
Some feedback:
I think this is very clean, now the preferences for the user are more visible.
Maybe only the second entry „User profile“ is already too much. 

I'm not an UI design expert, but here are my other thoughts:
The button „User profile“ points to the profile tab under the User profile page, which is a bit confusing from the names.
Maybe its better to combine the tabs Profile, Password, API, Roles, Preferences to only one Preferences tab (because Profile, Password, API and Roles are some form of preferences..). So that in the User profile there is only one Overview/Statistics of the User (for that click on the User Icon) and one Preferences for the User (click on the Preferences).

Let me explain it in some other way: The right expandable section, which you changed has some buttons which corresponds to the tabs at the User profile page, but there are not enough buttons to express the other tabs (Password, API, Roles), which is not great. But I would not add them in the right expandable section neither. That's why I propose the following:

![screen](https://user-images.githubusercontent.com/6190906/47388908-afe26380-d713-11e8-93fc-7d5e4b344979.png)

If you do not want consider this... that's not a problem, its ok as it is now with this pull request. So thanks!

**Comment by geniusupgrader** [comment]
Alright, good arguments, convinced.
But please consider removing the button „User profile“, as shown in my picture.
