### ISSUE TITLE
Columns on small/narrow displays (mobile) on „my times“ page

### ISSUE THREAD

**Issue by robinrosenstock** [kimai/kimai#370]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I look at the times overview on my mobile phone. On small, narrow displays only the following columns are shown: Date, Begin, End and the Action buttons. But I want rather see the Activity Name and the Duration (and Action buttons of course). See Picture for the problem:

![ddada](https://user-images.githubusercontent.com/6190906/47392066-c42a5e80-d71b-11e8-8710-bcf640d7167c.png)

**Describe the solution you'd like**
Because there is way too little space there, some columns needs to vanish. So to find a solution to this problem is not that easy.
But maybe set the order of the columns and then the columns on the right will vanish first (except the Action buttons) when the display gets more narrow.

**Additional context**
For this to work there must be a setting to reorder the columns. Or even reorder them with the mouse?.
I will open a new Issue for that.

**Comment by kevinpapst** [comment]
I added a PR that addresses this issue, could you test it and leave your feedback?

**Comment by geniusupgrader** [comment]
I will test it and give feedback shortly, thanks

**Comment by kevinpapst** [comment]
Oh and please think about if #371 is still needed, if you have full flexibility about which columns are displayed.

**Comment by geniusupgrader** [comment]
I have tested it visually (without looking at the code) on desktop pc and mobile phone. Here is my feedback:

Yeah! My initial problem is mostly vanished:
Now I can choose, the (important) columns on my phone!

But the settings are a bit confusing for me: At first I had thought, that you can define Phone/Tablet/Laptop/Desktop at one place and it is saved to the database and I've wondered why it is not changing on my mobile phone. But these settings must be set on each device individually! (I've overlooked the notice that it is stored in a browser cookie...). And this makes it really confusing, because I need to guess which setting applies for my device right now. It would be easier, if there was only one tab and the differentiation between Phone/Tablet/Laptop/Desktop would be abandoned. Because with a cookie this setting is already saved on exactly this device and there is no need to have settings for all four kinds of devices (Phone/Tablet/Laptop/Desktop) on every device. Can you elaborate which design goal you had in mind with this?

Except that these four tabs make it too complex, all is good and fine! Many thanks for it!

**Comment by kevinpapst** [comment]
Damned, I got confused down the road... because I was testing the different sizes on my development machine by resizing the window. So stupid by me, you are totally right => normal user will use it on one device and set their preferences once without the need to change it (for different sizes).

The only real use-cases I could think of are:
- switching the views on a phone/tablet between portrait and landscape
- resizing the browser window

To me, making it simpler to use is more important than supporting edge use-cases (10%).
Being able to de-/activate all existing columns should be sufficient, I was "work blind".

Very valuable feedback 👍 will remove the tabs.

**Comment by geniusupgrader** [comment]
When changing to another account (for example susan_super to clara_customer) the column settings from susan_super persists. Not so nice, when working with different people on the same computer...

Other than that: all fine.

**Comment by kevinpapst** [comment]
Still room for improvement, but step by step ;-)
