### ISSUE TITLE
Web UI and API: Description vs comments

### ISSUE THREAD

**Issue by itkfm** [kimai/kimai#3765]
### Describe the problem

Kimai2 v2: `d0e6feea50f65f973deb252060932a070b705934 @origin/release-2.0-beta2`

(Applies to *projects* at least, haven’t looked into other entities with regard to this.)
What Kimai (the HTML web interface) calls “description” is called “comment” in API responses.
What Kimai calls “comments” appears to be unavailable via the API.

### Describe the solution you'd like

- Unambiguous and consistent names/terms
- A way to retrieve the actual comments (for the sake of completeness)

### Describe alternatives you've considered

Lack of comments in API responses doesn’t matter to me for now.

Having the description available via “comment” works as well, as long as one’s aware what’s going on.

**Comment by kevinpapst** [comment]
Yeah, I know. Some sins of the past are hard to correct without breaking too many implementations out there.
So as you noticed (and besides the misleading naming) the "comment" field contains the description.

There is nothing I will do about that. 
I am not breaking all sync processes out there, that would be worse compared to a field with a funny naming.

I know that is not completely satisfying, but sometimes we have to make a compromise.
At least the API docs say what it really is:

<img width="665" alt="Bildschirm­foto 2023-01-17 um 16 57 08" src="https://user-images.githubusercontent.com/533162/212946950-7fc874a3-5838-4af1-9dd4-6717b3a2b573.png">

**Comment by itkfm** [comment]
Thanks for the explanation. v2 could have been an opportunity to fix this apart from other breaking changes.
But if this part of the API is backward compatible, then yeah, rather don’t break it for this “cosmetic” thing.

**Comment by kevinpapst** [comment]
Yes, agree. But breaking plugins is a little different from breaking integrations IMO.
Developers had to touch their plugins anyhow, because keeping BC here was impossible and then I thought: a hard cut and then a couple of years silence is better than constant changes over multiple releases.

But all the companies that have sync in place having to change their scripts ... I don't like the idea.

Good thing: the API was not yet released as 1.0, so there is always room for breaking changes in the future 😁
