### ISSUE TITLE
translations in v2

### ISSUE THREAD

**Issue by BeckeBauer** [kimai/kimai#3787]
### Describe the issue

Following the instructions under [https://www.kimai.org/documentation/local-yaml.html](https://www.kimai.org/documentation/local-yaml.html), I tried to modify the translation for an existing language. However, I got the following error:

```
 [ERROR] Unrecognized option "translation" under "kimai.theme.branding". Available options are "company", "logo",
         "mini", "title".
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by kevinpapst** [comment]
Thanks for the heads up 👍  I changed the documentation.

And I have bad news: that feature was removed. 
It caused a lot of headaches on my end and performance issues on every installation out there, due to the technical implementation.

You have three options now to change / add translations: 
- patch the core files 
- build your own plugin
- use the translation plugin (send me en email)
