### ISSUE TITLE
Invoice Grouped by Activity

### ISSUE THREAD

**Issue by srdco** [kimai/kimai#379]
We create invoices and summarize how we spent the time. For example, we bill for 10 hours - 2 hours spent on Analysis, 4 hours on Drafting, 1 on Client Communication, etc.
It appears that the Kimai v2 Invoice templates only allow lumping everything together into a single entry or break it out into every single time entry.

Is there any way that the invoice templates could allow summing time by activity?

The current workaround is to print or export a detailed invoice and create our own, but it would be much easier to simply use the native Kimai invoice system.
It doesn't seem like it would be hard to sum by Activity, but I may be wrong?

Thanks a bunch!!!

**Comment by srdco** [comment]
If you could give some pointers on where one would go to start editing that, I might be able to try taking a stab at it.

**Comment by kevinpapst** [comment]
That should be real simple to add! Copy this file and change the marked lines (+ rename the file, class and id):
https://github.com/kevinpapst/kimai2/blob/master/src/Invoice/Calculator/UserInvoiceCalculator.php#L34-L37
Afterwards clear your cache, otherwise the new renderer won't be picked up by the UI.

**Comment by kevinpapst** [comment]
I created a pull request, that will add an invoice calculator which groups entries by their activity.
If you want to test it: #380 - checkout the branch, clear the cache and create an invoice with it.
