### ISSUE TITLE
How to pull Expense Category onto an Invoice Template

### ISSUE THREAD

**Issue by TGG-RPA** [kimai/kimai#3828]
### Describe the problem

We purchased the Expense Plug In, which seems to be working so far.  That said, is there a way to bring in the Expense Category in an invoice template?  The debug script does not include Expense objects so we were unsure where to pull if at all available.

e.g., Expense Category - Admin Fees

Currently, when this is pulled into an Invoice, it does not include the Expense Category.

### Describe the solution you'd like

To be able to display Expense Category when applicable on the invoice.

**Comment by kevinpapst** [comment]
Next time pleas post plugin discussions in: https://github.com/kevinpapst/kimai-plugins

The README.md of the Expenses plugin contains that information:

----------

As expenses will be automatically included in your invoices, you might want to distinguish between expenses and timesheets.

Since Kimai 1.6.2 and ExpensesBundle 1.5 this can be done with the invoice template variable `${entry.type}`.
The value will be `expense` and can be used for example in Excel with `ifthan` formulas or in combination with a `conditional format`.

The invoice template variable `${entry.category}` will contain the category name of the expense.
