### ISSUE TITLE
"My working hours" on Dashboard is too large when you use it with small window.

### ISSUE THREAD

**Issue by stgpepper** [kimai/kimai#3859]
### Describe the issue

I my workflow I resize the window to very small so I can keep it open all time and it wont use up real estate on my monitors. 

**How it used to work:**
Before the update I could see the whole "My working hours" widget. Now it shows only part of it when my window is very small. I had the refresh the page after resising it small so that the widget would scale to fit the area available.

**How it seems to work now:**
It seems to resize vertically, but not horizontaly. Not even when I refresh the page. See picture attached.

**Does this NEED fixing**
Probably not. It is a minor inconvinience. It also seems that the whole dashboard is more easily customaisable and I still would brefer that over the lost widget resize capability (if it is a tradeoff thing).

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0

### How do you run Kimai?

KIMAI CLOUD

### Which PHP version are you using?

Unknown

### Screenshots

![kuva](https://user-images.githubusercontent.com/74211382/220160015-4058c95a-336b-474f-87b5-4a86e0aee2f9.png)

**Comment by kevinpapst** [comment]
While I agree that it would be favorable that every screen size works perfectly, it is simply not supportable. 
There are always certain edge case sizes that will break expected behavior.
It works good on mobile, so more vertical space is easier to scale than screens with a tiny height.

Resizing the window does not properly scale the chart. 
That is unfortunately unfixable for me, it is how the charting library works with the current size settings. 
As you say: reloading the page once after resizing the browser fixes it.

The chart has currently a height of 300px. 
If you find a better setting (check source code with developer tools for a canvas called "DailyWorkingTimeChart_xxxyyzyzzzzyzyzzy"), e.g. using relative values, I'd be happy to adapt it.
Until then I will close this as "works as expected".
