### ISSUE TITLE
Start clock immediately

### ISSUE THREAD

**Issue by sollermun** [kimai/kimai#3891]
### Describe the problem

It would be great if there was a feature to just hit the "play" button immediately to pause whatever else I am working on and start measuring time for a new entry. Sometimes, a telephone call will come in that I need  to take or I need to immediately change tasks.

Ideally, you would be able to start the clock immediately and fill in all of the details later, re:  project name, task, etc., when the timer is stopped.

Also, a pause button for things like bathroom breaks would be nice.

### Describe the solution you'd like

I would like the timer start to be able to immediately begin measuring time and fill in all of the details for the time entry when the clock is stopped. 

A pause button would also be great so that there aren't multiple entries that show up on the invoice.

**Comment by kevinpapst** [comment]
There is the "restart one of your last activities" dropdown (next to the start button), that is doing what you want.
Creating empty timesheets is not possible, due to the data structure.

A pause feature was requested before, vote for it with 👍 

Also: do not mix multiple requests in one, otherwise they'll get lost.
