### ISSUE TITLE
Show 2FA token in plain text below QR code

### ISSUE THREAD

**Issue by TheZoker** [kimai/kimai#4006]
### Describe the problem

Currently the 2FA token is only displayed as QR code. While this is fine for phones, it's not really usable for PC applications. Many password managers have the ability to add a 2FA token via text (if this is secure and should be used, is another discussion). 

### Describe the solution you'd like

Most applications that display a QR code for a 2FA token, also show the token as clear text below the QR code. This would also nicely work for kimai.

**Comment by kevinpapst** [comment]
Showing the QR code is considered bad practice (insecure) and afaik the RFC says that it should not be done, because it should not be available via plain text. I am not sure how I think about it. 

It's easy to display, but 2FA is already "edgy" from a consumer perspective (outside of the tech bubble). 
Showing a 160+ character long code makes it even worse.

Can you name some applications that support QR codes, I'd love to test them. I only use Aegis on my Android phone, besides that I know Google Authenticator.

**Comment by TheZoker** [comment]
Sure, here are some examples:
- Gitea: 
![image](https://user-images.githubusercontent.com/1368405/236066487-8425bdd0-3968-4f78-91fd-341bcb64f383.png)
- Github (can't show an screenshot here, but just visit https://github.com/settings/security?type=app#two-factor-summary)
- HomeAssistant: 
![image](https://user-images.githubusercontent.com/1368405/236067223-01ee65e1-fd76-4a35-81a3-3f7287216ecd.png)
- Bitwarden
....

**Comment by kevinpapst** [comment]
Sorry, I meant:: which apps support entering the secret code directly.
So your password manager I assume

**Comment by TheZoker** [comment]
Ah sorry yes I see. So enpass allows that, bitwarden as well. But also Aegis

**Comment by kevinpapst** [comment]
In the next version, you can click on the QR code to display the (otherwise hidden) secret code.
<img width="302" alt="Bildschirmfoto 2023-05-30 um 16 39 20" src="https://github.com/kimai/kimai/assets/533162/8a9c3eb0-f311-4856-b1f5-e6f5b80fd47a">
After the click:
<img width="536" alt="Bildschirmfoto 2023-05-30 um 16 39 25" src="https://github.com/kimai/kimai/assets/533162/3f12c7dc-2e18-4eb3-b54b-7de3c95e9150">
