### ISSUE TITLE
Changing activity, changes the current recording activity

### ISSUE THREAD

**Issue by fazaldegui** [kimai/kimai#408]
I select an activity, ex: "Act1", and press the green Play button, a new entry appear in the registration window and the red Stop button appears.
In that state if I change the selected activity, in the bottom-right window, ex: "Act2", the activity that is actually recording changes to "Act2"!!
This is a surprising behaviour, I expected that the recording activity will be continued to "Act1", the one which I selected when the green Start button was pressed, and not to change.

To change the entry activity I have the "pencil" icon next to the entry.

Kimai version: v0.9.3.1384

**Comment by laplix** [comment]
OK for me to change by configuration. I use Kimai for my personal projects and I make mistakes. I use this feature to change the client/project/task (whatever) for the current time. I find that this is an important feature for me since I'm working on many projects.
Having it in configuration (default to what it is now) is OK with me.

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
