### ISSUE TITLE
Default setting for "mark as exported" in export dialog should be *no* or somehow customizable in server settings

### ISSUE THREAD

**Issue by urmel1960** [kimai/kimai#4088]
### Describe the problem

If you get a hit list in the export dialog, the switch to select if the found records should be marked as exported is set to "on" by default. If you look at the export now, in this case the records are all marked as exported. 

However, you often only want to view the export once and check it in the export-template before performing the final export.  If in these cases you overlook to deactivate the switch, you have to rewrite all found datasets as "not exported".

### Describe the solution you'd like

The default setting for "mark as exported" in export dialog should be *no* or somehow customizable in server settings

**Comment by kevinpapst** [comment]
I am not considering to change the default value due to reasons.

But I can give you some hints, so you can do it:

- After showing any export preview, you can save the search as default IMO. 
- Or you could use a custom javascript to set the value to off by default.

Maybe I will reconsider in the future, but for now I have reasons to keep it like that.
