### ISSUE TITLE
Reject configuration files with unknown file ending explicitly

### ISSUE THREAD

**Issue by brickhousewindow** [kimai/kimai#4105]
### Describe the problem

When a configuration file is being used with a not used file ending, e.g. .yml instead of .yaml, the file is included inside the cache preload but is not activated.

`Reloading configurations ...
============================

 // OK in config/routes/test/test_routes.yaml

 // OK in config/routes/dev/twig.yaml

 // OK in config/routes/dev/web_profiler.yaml

 // OK in config/services.yaml

 // OK in config/packages/twig.yaml

 // OK in config/packages/jms_serializer.yaml

 // OK in config/packages/security.yaml

 // OK in config/packages/translation.yaml

 // OK in config/packages/local.yml <---

[...]`

If the wrong extension is used but is not being reported the user starts looking for mistakes and errors where no errors are.

### Describe the solution you'd like

The application should reject unknown or unused extensions during a cache refresh. For example displaying a warning or including it inside the log output.

And/Or the application should make use of the extension .yml. This extension is the second official used one (https://en.wikipedia.org/wiki/YAML). It is also used by ansible (https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html), which many administrators use.

**Comment by brickhousewindow** [comment]
When refreshing the cache, independent whether a file is ending in .yml or .yaml the counter does not change:
`[OK] All 26 YAML files contain valid syntax.`
Renaming to file to .json decreases the counter. Would not this mean that it is actually a bug that a file is being included but not activated ? Why should the configuration loader report it otherwise ?

**Comment by kevinpapst** [comment]
This is NOT the loader. This does also NOT indicate that the named file is being loaded.
This is simply a validation routine that checks the YAML syntax.
You can't believe how many support requests I had in the past, because people did not count their spaces.

For that reason (and also because this part of the framework I am using) I cannot change anything about these messages.

I appreciate feedback and ideas, don't get me wrong here! 
But you are overthinking that issue: if 5 people a year run into such an issue, it is not worth thinking about it.

Also nobody ever sees these messages, unless they fiddle around with log settings.
That is default output:
<img width="730" alt="Bildschirmfoto 2023-06-12 um 17 11 55" src="https://github.com/kimai/kimai/assets/533162/ca4685bd-32b6-40b5-b98d-60d8e14ad77a">

I'll change it to:
<img width="665" alt="Bildschirmfoto 2023-06-12 um 17 12 42" src="https://github.com/kimai/kimai/assets/533162/3db64b76-d53c-474e-b93c-4eea78a0a225">
