### ISSUE TITLE
Usability flaw in form "add_edit_timeSheetEntry"

### ISSUE THREAD

**Issue by kboss** [kimai/kimai#417]
On adding an new entry the selected projectID is not brought to the viewport of the selectfield (as opposed to the activityID). This behaviour is also the same on editing a timeSheetEntry: the activityID comes to the viewport, the projectID does not.

The abovementioned is a bit confusing when you have lots of projects in your list and dont immediatly see the choosen one on editing or adding an entry.

**Comment by kevinpapst** [comment]
If you mean that the projectID is/was not highlighted/selected in the dialog, this is fixed in the latest master. I am closing this issue. Also the project list scrolls down to the selected project, so this was either a browser bug or has been fixed in the meantime.

If your problem still remains, just drop an answer with more details and I will reopen it.
