### ISSUE TITLE
Date and time formatting

### ISSUE THREAD

**Issue by robinrosenstock** [kimai/kimai#419]
**Is your feature request related to a problem? Please describe.**
After changing the language (multiple times) I noticed that the date and time formatting is connected with the language setting. But I would like to set the date/time formatting freely without being forced to use the formatting of my language locale setting.

**Describe the solution you'd like**
An option in the preferences to change the date/time formatting would be sufficient

**Comment by kevinpapst** [comment]
You can change the formatting if you want:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L44

But IMO this is not something a user should be able to configure.

**Comment by geniusupgrader** [comment]
> You can change the formatting if you want:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L44

Thanks for pointing me there.

> But IMO this is not something a user should be able to configure.

I think it **is** a legitimate user setting. After all it is for the user interface and for the end user, which is not comfortable with specific time/date formatting. There might be even mistakes in this regard, for example when someone is reading a date and he confuses the day with the month because the formatting is unfamiliar for him.
I have seen so many applications and software, which allow to set the formatting of time and date (as a user). And it would be beneficial for companies with guidelines or policies, which enforces specific time/date formatting

**Comment by lduer** [comment]
As far as I know there are different rules/norms/standards in every nation for displaying dates. e.g. https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates or https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe#Date_2 with YYYY-MM-DD (although in german speaking regions DD.MM.YYYY is widely used - I don't know the specific standard)

In business cases, these regulations should be followed to simplify internal end external communication.

> I have seen so many applications and software, which allow to set the formatting of time and date (as a user). And it would be beneficial for companies with guidelines or policies, which enforces specific time/date formatting

I understand your point of view but it does not simplify the users options and possibilities. I also think that this could be a "plugin".

**Comment by kevinpapst** [comment]
Closing as this will not be part of the core. If anyone wants to work on this as a plugin, I can help with insights on how to start.
