### ISSUE TITLE
Small visual issue with arrow date selectors

### ISSUE THREAD

**Issue by SaturnusDJ** [kimai/kimai#4215]
### Describe the issue

For date selectors (invoice, filter), the following happens in at least Firefox and Chrome:

![image](https://github.com/kimai/kimai/assets/14320018/d2c5be4a-8792-4424-8dd5-b46ecd06f36c)

It's like the arrow button loses border.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.29

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

**Comment by SaturnusDJ** [comment]
I see it is happening to more fields. For example when trying to add a record to a locked period, the border becomes highlighted I think? This highlight is like above, only top and bottom, not the whole field. (Kimai 2.2.1.)

![image](https://github.com/kimai/kimai/assets/14320018/c7d1ea0e-f64d-4d2d-a3a8-df6c9081c4f1)

**Comment by kevinpapst** [comment]
Yeah, annoying. This happens since I switched from these fields:
<img width="162" alt="Bildschirmfoto 2023-11-06 um 13 33 57" src="https://github.com/kimai/kimai/assets/533162/a3da7f55-6f8b-4962-a19a-d851d02f0bb8">

to these:
<img width="176" alt="Bildschirmfoto 2023-11-06 um 13 34 20" src="https://github.com/kimai/kimai/assets/533162/65e119e9-6c77-443e-94be-a06e29c76cd5">

Maybe I have to revert these changes

**Comment by kevinpapst** [comment]
New release 2.12 will revert to the previous format.

Doesn't look that good IMO, but does fix all these tiny issues.
