### ISSUE TITLE
Different working hours during summer & winter

### ISSUE THREAD

**Issue by meulie** [kimai/kimai#4294]
### Describe the problem

Perhaps a somewhat special use-case: different hours during the summer months.

September-April: 08:00-16:00
May-August: 08:00-15:00

### Describe the solution you'd like

The option to specify two/multiple work hour ranges

**Comment by kevinpapst** [comment]
Thanks for the purchase 👍 

Problem I see: the next one wants different shifts during school holidays ... unless you make it super-flexile, there is always one more use-case that cannot be full-filled. And that is against the KISS principle of Kimai.

My only idea is to create an API endpoint that allows to change the configuration, then you can trigger a script twice a year that changes the user configuration and thus prevents the manual and error-prone overhead.

**Comment by Swoy** [comment]
Hello Kevin,
_( I just bought the plugin Working hours, vacation, sickness (controlling))_

Let me weigh in on this issue, a lot of administrative institutions around the globe use multiple target hours during summer and winter seasons. I don't think the suggestion is unreasonable.

A a super flexible way to solve this _(that will solve any case except maybe granulated hours on a single day)_ could be to allow us to define _target hour profiles_, with arbitrary ranges of dates and hours. Then we can add these profiles to teams or individuals. Examples as follows:

1. Profile 1: Every monday from 01.01.2023 to 02.02.2024 has a target of 08:00 hours | Tue - Fri has a target of 07:30
2. Profile 2: Mon-Fri from 01.09.2024 to 01.05.2025 has a target of 07:45
3. Profile 3: Mon-Fri of week 15 has a target of 05:30 hours

If an admin user assign two profiles to the same entity, the order they are added can matter, Say if you assign P2 and P3 to a team, week 15 will override P2 and have a target of 05:30 per day, but for the rest of the P2 range, the target will still be 07:45. This way you could create perpetual ranges, like so:

4. Profile 4: First day of Sep -> Last day of May = target hours 07:45
5. Profile 5: First day of Jun -> Last day of Aug = target hours 07:00
6. Profile 6: Week 18 -> Week 19 = target hours 06:45

Or even:

Profile 7: Mon, Wed, Fri = TH07:45 | Tue, Thu = TH07:00

For instance, I guess these overrides will work much like holidays do now?

Another option _(and potentially a workaround)_, would be to allow us to configure target hours on a per project basis, but for each individual assigned, and per day (instead of monthly or lifetime as it is now). This way, we can create multiple projects named "Normaltime (winter)", Normaltime (summer) etc. And provide the targets that way.

I can list more ways to solve this, but I think you get my point :)

**Comment by Swoy** [comment]
Does the ❤️ imply that this suggestion will be considered? As it stands now, we are unable to use this product because our plus and minus time will be incorrect due to the difference in target hours between seasons.

**Comment by kevinpapst** [comment]
I always consider suggestions, which doesn't mean I will fulfil every wish. 
There is a roadmap and I added you input to the list of ideas, see the "Idea section" at this page:
https://www.kimai.org/store/controlling.html

There is already a workaround existing:
Whenever you close a month, Kimai will store the data including the expected hours for each day.
That means, that you can change the expected hours currently 12 times a year.
Just make sure to approve the month before changing it.
Do that, whenever there is a switch from summer to winter time and everything should be fine.

And this is already on the idea list:
Approval of partial month, to allow switching the contract settings at an arbitrary date.

**Comment by kevinpapst** [comment]
Closing here. 
You can find all ideas in the shop page at https://www.kimai.org/store/controlling.html

Please post future ideas for paid plugins at https://github.com/kevinpapst/kimai-plugins
This issue tracker is for core Kimai.
