### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by robjuz** [kimai/kimai#4318]
### Describe the problem

Hallo @kevinpapst 

I have a suggestion about the versioning. 
could you please bump the minor version on „breaking“ changes like the database url? 

I‘m maintaining the helm chart for kimai and follow all releases to see if I need to adjust something in my Projekt. 

### Describe the solution you'd like

Patch releases should not require any intervention. In my personal deployment, I just change the docker image version and redeploy.  
It‘s ok for major and minor releases. I update the chart to reflect the change and update the default docker version. 

I hope I made myself clear.

Thx!

**Comment by kevinpapst** [comment]
Agree. I do not stick with Semver versioning, because there are BC changes in almost every release in the internal APIs. 
They just don't affect anyone.

In that special case the serverVersion was even in the .env file since Kimai 1.x:
https://github.com/kimai/kimai/blob/1.x/.env.dist#L3
Everybody just ignored it, until it wasn't able to ignore it any longer 🤷 

The "URL change" was something special and forced upon us through dependency updates from Symfony.
I found out myself only after the release through user complains as I didn't have any issue in all my installations, because I always had the serverVersion in the DATABASE_URL. 

Thanks for maintaining the image ❤️ 

And yes, I am trying to do better. Can't promise though that I will catch everything in every release. 
I guess there is nothing that I can do here right now, so I am closing, okay?
