### ISSUE TITLE
Use composer-binary image

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#4397]
### Describe the problem

Replace the current usage of the composer/composer image with https://blog.codito.dev/2022/11/composer-binary-only-docker-images/

This will reduce the download size from 180MB for that build step to 3MB

**Comment by Not-Code** [comment]
Ok, this seems feasible but before opening a PR there are some points that I want to highlight.

The current artifact Kimai is using for composer is defined in the Dockerfile:

```
ARG COMPOSER_VER="latest"
...
FROM composer:${COMPOSER_VER} AS composer
```
and so this is the current distribution in use for [composer:latest](https://hub.docker.com/_/composer).
Approving this change would switch the distribution to this different artifact [composer/composer:2-bin](https://hub.docker.com/r/composer/composer/tags).

Both the distributions are related to the project [composer](https://github.com/composer/docker), but at the moment is not clear to me if there are major differences between the 2 (other than the speed of releasing: _composer/composer:2-bin_ should appear before the _composer:latest_ during a new version release).

On the docker side, a major difference is that _composer:latest_ produces images for different architectures while _composer/composer:2-bin_ produces images only targeting amd64.
This, that should be a major issue for Kimai (that is producing images both for amd64 and arm64), is in reality something that doesn't seem to have any kind of effect during a multi-architecture build, other than the warning:
`WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)`

My guess is that, being PHP an interpreted language, they can release composer (that from what I've seen has only PHP as a requirement) with just one distribution and be used everywhere.

Last thing that I want to advise is that I cannot directly test an arm64 container because I don't have an arm64 device. 

If all things considered we want to proceed, I can open a PR towards branch release-2.10.

**Comment by kevinpapst** [comment]
Seems the blog post can be opened, well anyways: I just read the article and thought it might be worth investigating. I think the outcome of the article was a much smaller image.

Thanks for doing the investigation, that helped a lot to understand it, bravo 👍 

The smaller image (with 1M downloads) says:

> Non "official-images" build of Composer container, same as the "composer" one with faster releases 

While the one we are using right now (with 100M downloads), has a badge that says:

> Docker Official Image

But from what I have read now, it seems that this mostly relates to the policy of "official docker images". Both versions should be reliable and are tagged and pushed from the same workflow. So no big risk I guess.

Are you willing to test if the different composer image has any benefit for the Kimai image? I am in no position to decide if such a change has benefits and I don't want to make a change only "because we can" 😁 

I can only spin up an arm64 container on my Macbook, if you tell me what to check for.

**Comment by Not-Code** [comment]
yes, that's pretty much my undestanding too. But the devil is in details and so I preferred to hear your opinion.

Well, we have 2 points to consider. The first one is directly from [composer documentation](https://getcomposer.org/doc/00-intro.md):

`Important: short-aliased images don't have binary-only equivalents, so for COPY --from approach it's better to use composer/composer ones.`

Beats me, why they're suggesting it but they should know better, right?

The second one is it that, other then this composer comment, the benefit from Kimai point of view is exactly the one you described. During builds instead of downloading the big 196 MB image, you will download the small 2.87MB. But that will not have any effect for Kimai images that will remain of the current size.

This is a Dockerfile that is moving composer/composer:2-bin

```
FROM composer/composer:2-bin AS composer

FROM alpine:latest
COPY --from=composer /composer /usr/bin/composer
```

Where the copy layer has history:

```
ID                                                                CREATED         CREATED BY                                                                                                          SIZE        COMMENT
4630d2200cc97e791fd534d52a15fbcd9c01cc4c72dcbe55061ad524c9ca9f99  52 seconds ago  /bin/sh -c #(nop) COPY file:ed862a9138d216d5673f0a5f00f6108be729428b4b0267b6527947f37b505119 in /usr/bin/composer   2.87MB      FROM docker.io/library/alpine:latest
```

This is a Dockerfile that is moving composer:latest (current version of Kimai)

```
FROM composer:latest AS composer

FROM alpine:latest
COPY --from=composer /usr/bin/composer /usr/bin/composer
```

Where the copy layer has history:

```
ID                                                                CREATED         CREATED BY                                                                                                          SIZE        COMMENT
9c175d209b48dd3eddf9ed71f0bf6421f160fd1d35aeb120354d2050b3f54714  21 seconds ago  /bin/sh -c #(nop) COPY file:ed862a9138d216d5673f0a5f00f6108be729428b4b0267b6527947f37b505119 in /usr/bin/composer   2.87MB      FROM docker.io/library/alpine:latest
```

They're moving the same file. So, yeah... Unless downloading 196 MB is an issue there is no difference between the composer versions (I even checked with sha512sum in the filesystem and yes, they are indeed the same file).  From another point of view this indirectly confirms that the change should be safe with no regressions, and from code perspective we are talking of 3 lines in the Dockerfile.

**Comment by kevinpapst** [comment]
Sounds like: we have no real benefit ... well, besides the "environment" by saving around 190MB download.
Are these layers cached ? Or re-downloaded ?
This looks like 5s for the download: https://github.com/kimai/kimai/actions/runs/7480111243/job/20358814351#step:7:250

Hm, I know I opened the issue, but I am not sure anymore if it is worth the change.

**Comment by Not-Code** [comment]
Well, docker download images only one time and after that you have it locally. Additional pulls (unless the image has changed in the registry) are not going to be downloaded again. In reality it's even smarter than that. Every layer that composes an image has a specific identifier. So if you pull 2 different images that have some layers in common (ex. the base os), it will not download those common layers again (if you already have them in your local repository).

Still here we are talking of CI/CD and whenever a new job starts the VM or the container (in case of Docker in Docker build) is generally in a clean state (unless you are synchronizing a cache).

In Kimai case you have 4 jobs:

build (dev, fpm)
build (dev, apache)
build (prod, fpm)
build (prod, apache)

and every one of these starts clean. If you look at the logs you will see the download of composer 2 times per job:

**AMD64**
```
#14 [linux/amd64 composer 1/1] FROM docker.io/library/composer:latest@sha256:1f88162f6d30fe394990edd298f181f66e8a4ba36d3e102213c2d4a8eb8654a5
#14 sha256:8efd93cef2cf149b81400aff0a11b7294bc336566f9b97fa5e399e11a31156bd 126B / 126B 0.1s done
#14 sha256:4b1cd4fd5b56696c7161320775e3b4744d5a2e333c6d071daeee9368f059649a 417B / 417B 0.0s done
#14 sha256:594b5f962aa61040688e8c344aba5b32c6ef46a8fccf1b57b50260af3966fe34 265B / 265B 0.0s done
#14 sha256:00dba960c1f97c321c9c9b441ac0d9983abadd6fd091fd5d823b12fa07b2e01d 1.31MB / 1.31MB 0.1s done
#14 sha256:74b1388b45b1ff44be24bc5c4450ecf6731f698fd0189d6560a[285](https://github.com/kimai/kimai/actions/runs/7480111243/job/20358813928#step:7:290)728a0312a2 19.29kB / 19.29kB 0.0s done
#14 sha256:64252f72f3b7f569d0824c7e6e85c77f6996a2a23c1e0ac2eac4bc0bc2a71c20 2.45kB / 2.45kB 0.0s done
#14 sha256:9c89438a3af7fa920ae38a4db8d3af3a75255d7fc2f3218abc7441df47dece1c 497B / 497B 0.0s done
#14 sha256:f96fa6dac3203e154cea18ae513638d349375e628a4c9b1321009999f26e8632 32.68MB / 32.68MB 0.4s done
#14 sha256:032cda9d3dcea536b0398720b48c829672073360aa49163574c08[289](https://github.com/kimai/kimai/actions/runs/7480111243/job/20358813928#step:7:294)6af3b3c3 17.24MB / 17.24MB 0.2s done
#14 sha256:0d66ed8a08e88da3eb191d4a92354afb44aa32afeb70a35f017bb21e4d476a42 12.47MB / 12.47MB 0.2s done
```

**ARM64**
```
#20 [linux/arm64 composer 1/1] FROM docker.io/library/composer:latest@sha256:1f88162f6d30fe394990edd298f181f66e8a4ba36d3e102213c2d4a8eb8654a5
#20 resolve docker.io/library/composer:latest@sha256:1f88162f6d30fe394990edd298f181f66e8a4ba36d3e102213c2d4a8eb8654a5 0.0s done
#20 sha256:c5d57f6a6076d4abe068a64eb176f7d9bc3492e3fff93c98891076474784bf20 126B / 126B 0.0s done
#20 sha256:902a1567a93c0c24861925cbfeb912fae0053b8cad837b2285176a5c8ea81722 417B / 417B 0.0s done
#20 sha256:28bba3ab360755f3b286c56196afa17d5006c802376730718befa36ca314c5b3 1.31MB / 1.31MB 0.1s done
#20 sha256:9ad6e240f09d2e04e5f78bad4bb5853719cb7cbd7851c390711d7f1740139604 [266](https://github.com/kimai/kimai/actions/runs/7480111243/job/20358813928#step:7:271)B / 266B 0.0s done
#20 sha256:d0cfdabc37df1900b7881f01fed7201c95360c004bf90ebbad00ca372c2cbf57 19.08kB / 19.08kB 0.1s done
#20 sha256:aa64ecb8fa41b54ab49204e2f9ef993e7bfb9fb9bd93838140b5f9ebe89f8d4d 2.45kB / 2.45kB 0.1s done
#20 sha256:c99ea0c23138b6e1c542537b1c450d3bce562193a95f17257c2e0b18fcddbbf2 33.19MB / 33.19MB 0.4s done
#20 sha256:9019e34eb849acaf850d10f4075f93eeb506c919f80f4e5c39c2b2a15cae4773 497B / 497B 0.1s done
#20 sha256:4ed22edfdb10a36cd9b58e853dc177e6e9e106ad104ee5c6f3d3bbdc5c8dcd5b 17.21MB / 17.21MB 0.3s done
#20 sha256:def0554f9c72eaae677cdb5ee1323dac94b472cbca4b0601ea86130b1c163546 12.47MB / 12.47MB 0.2s done
```

So the CI/CD is downloading this a total of 8 times. A docker pull with layers already present will tell you that very clearly (this is podman but docker does the same, maybe with a different log).
```
$ podman pull docker.io/library/composer
Trying to pull docker.io/library/composer:latest...
Getting image source signatures
Copying blob 9c89438a3af7 done   | 
Copying blob 661ff4d9561e skipped: already exists
Copying blob 47536423e079 done   | 
Copying blob 1be6d4fc569f done   | 
Copying blob 0d66ed8a08e8 done   | 
Copying blob fbc99979baa6 done   | 
Copying blob 032cda9d3dce done   | 
Copying blob 64252f72f3b7 done   | 
Copying blob 74b1388b45b1 done   | 
Copying blob f96fa6dac320 done   | 
Copying blob 594b5f962aa6 done   | 
Copying blob 00dba960c1f9 done   | 
Copying blob 4b1cd4fd5b56 done   | 
Copying blob 8efd93cef2cf done   | 
Copying config 1304add120 done   | 
```

To me, even with these evaluations, the change still looks like a meh change. If we were in the '90s with this I would clearly have a different opinion 😁

![image](https://github.com/kimai/kimai/assets/18069705/f87f2ffa-50c7-4bca-a704-fdf799c9f1e2)

**Comment by kevinpapst** [comment]
Okay, lets close it as `Meh` then 😈 

Even though there is no doing now, the outcome was worth it.

Thanks for your investigation and support 👍
