### ISSUE TITLE
replace all selects with smart-selects and live-search

### ISSUE THREAD

**Issue by j0hannesr0th** [kimai/kimai#441]
**Is your feature request related to a problem? Please describe.**
Imagine having 200+ customers with 400+ projects and 50+ activities. Creating a new time entry becomes a bit messy because you have to search a lot until you find the right customer, project and activity.

**Describe the solution you'd like**
Consider adding something like this if it is available in the framework you use: [https://developer.snapappointments.com/bootstrap-select/examples/#live-search_1](https://developer.snapappointments.com/bootstrap-select/examples/#live-search_1)

**Comment by kevinpapst** [comment]
Sounds as if you want to give me your feedback on the beta test:
https://github.com/kevinpapst/kimai2/blob/master/var/docs/theme.md#searchable-input-types

**Comment by hmr-it-jr** [comment]
I've tried to test it but it wasn't able to make it work.

What I've tried: set the value of select_type to selectpicker and to 'selectpicker' because in the link it's mentioned without '' and in the comment above it's mentioned with ''.

Do I have to checkou a specific branch to make this work?

I've deleted my cache but it hasn't changed anything.

<a href="https://www.imagebanana.com/s/1251/E6SFhJpW.html" target="_blank"><img src="https://s1.imagebanana.com/file/181124/E6SFhJpW.PNG" title="Bild auf ImageBanana anzeigen"></a>

**Comment by kevinpapst** [comment]
It doesn't matter if you use `'selectpicker'` or `selectpicker`.
But if you change the value, you have to clear your cache, as the config is never compiled again in production, unless you trigger it manually: `bin/console cache:clear`

**Comment by hmr-it-jr** [comment]
Yes, it was the cache.

It works perfectly for me and that was exactly what I was looking for! 👍

**Comment by kevinpapst** [comment]
Could you please leave some feedback after a couple of days of usage.
I'd be especially interested in usability flaws and compatibility with mobile devices.
