### ISSUE TITLE
Docker test script fails (currently deactivated)

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#4503]
### Describe the problem

The last release failed partially to build Docker images:
https://github.com/kimai/kimai/actions/runs/7241462128

Additionally many tags weren't pushed:
<img width="759" alt="Bildschirmfoto 2023-12-20 um 16 58 21" src="https://github.com/kimai/kimai/assets/533162/0e2dc7d8-93ce-46ab-9812-1a0a62a428f2">

Unfortunately many of them are prod tags. 
So many are now missing the 2.6.0 build: https://hub.docker.com/r/kimai/kimai2/tags

Might be fixed by #4504

My biggest issue is that I do not know how to test this.

**Comment by kevinpapst** [comment]
@tobybatch my potential fix did not work. i tried to reproduce locally, wasn't able to. This is thrown in Docker build "Test lite":

<img width="758" alt="Bildschirmfoto 2023-12-26 um 16 51 02" src="https://github.com/kimai/kimai/assets/533162/e3d268a3-6cd0-45d2-b02f-69606e531d71">


Now if I change the BASTABASE_URL locally and remove the entire cache before calling `bin/console kimai:version` I am also able to produce an error (but not the same one).

With `DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/kimai.sqlite`

<img width="771" alt="Bildschirmfoto 2023-12-26 um 16 54 36" src="https://github.com/kimai/kimai/assets/533162/aa0a40b6-bf79-44c2-b1b8-df0bf8a1c1f3">

With `DATABASE_URL=`

<img width="1018" alt="Bildschirmfoto 2023-12-26 um 16 55 18" src="https://github.com/kimai/kimai/assets/533162/4cb81027-ca4c-4407-936f-79e0a73db8ba">

With `DATABASE_URL=mysql://kimai:kimai@127.0.0.1:3307/kimai2xxxxxxx?charset=utf8mb4` (invalid port and missing serverVersion!)
<img width="767" alt="Bildschirmfoto 2023-12-26 um 16 56 27" src="https://github.com/kimai/kimai/assets/533162/3767c133-ac48-4852-913a-f36bf6d159d4">

No matter what I do, an error only pops up, if Doctrine tries to query for the server version. 
And I do not understand why that should happen, as I changed the DATABASE_URL to include all required information.

What is that test-lite.sh doing anyway? Can we remove it and re-run the scripts manually?
Is the docker, which executes the test script, probably running without the required ENV information?

**Comment by kevinpapst** [comment]
Temporary fix: https://github.com/kimai/kimai/commit/c5dcf9e0fd057d1167c3754858d288f004b47b2f

Seems to have done the trick, so the latest version could be tagged and pushed 🤷

**Comment by kevinpapst** [comment]
@tobybatch can you give me a hint on how to debug that problem? 
Obviously that needs to be analyzed locally. But how?

**Comment by tobybatch** [comment]
I'm looking

**Comment by tobybatch** [comment]
@kevinpapst I think we can just remove the lines that were commented out in https://github.com/kimai/kimai/commit/c5dcf9e0fd057d1167c3754858d288f004b47b2f as we don't support SqlLite at all any more. Originally that would bootstrap the Kimai install and check it ran as part of the build process.

In the longer term I should set up the workflow to:

1. build and push the images as something like `kimai/kimai2:main-fpm-dev` etc.
2. test them with a _real_ mysql db
3. tag them as `latest`, `dev` etc only if the tests pass.

The naming main in that tag should maybe be changed to something else to indicate that the image may not be stable.

**Comment by kevinpapst** [comment]
Ok. Todo for me: delete that stuff. Can I also remove the test-lite.sh script alongside those lines?

Regarding the tests: if I can help, let me know how.

**Comment by kevinpapst** [comment]
I'll do it the other way around: reactivate the test-lite script and only deactivate the `bin/console kimai:version` test.
We should find out, why the DATABASE_URL is not available in that context.

**Comment by Not-Code** [comment]
Hi @kevinpapst,
if I understand correctly the issue is that after pulling kimai/kimai2:apache-dev you run the command `bin/console kimai:version` and this fails because DATABASE_URL is not set at that time.

If I got it right it seems that the issue is related to the [Dockerfile](https://github.com/kimai/kimai/blame/c5dcf9e0fd057d1167c3754858d288f004b47b2f/Dockerfile). Using git blame function I see that you updated the (line 241)

`ENV DATABASE_URL="mysql://kimai:kimai@127.0.0.1:3306/kimai?charset=utf8mb4&serverVersion=5.7.40"`

2 weeks ago.
But if you look respectively to the DEV build you can see (line 293):

`ENV DATABASE_URL=`

and to the PROD build (line 321)

`ENV DATABASE_URL=`

So you are effectively setting that parameter in the base image but it is then deleted in the dev/prod images. So if the test is run targeting dev/prod it should indeed find ENV DATABASE_URL not set.

**Comment by kevinpapst** [comment]
Aha, that explains a lot.

FYI: I have no clue what I am doing when it comes to Docker. I am building the app and usually @tobybatch is managing the Docker image. I was just blindly trying to fix the issue, which just popped-up, because Doctrine changed their behavior and now auto-starts a connection, if the DATABASE_URL does not contain the serverVersion (yes, even if the connection is not required).

I guess setting the DATABASE_URL for the prod image isn't the best idea?

**Comment by Not-Code** [comment]
Yes, it may not be the best approach because it would mean that anyone downloading that image and not setting the variable would just inherith the value in the Dockerfile. It would make sense if Kimai, by default, provided an image with an embedded database (i.e. SQLite), but if an external database is needed, then it should be the right move to delete the value for dev/prod images.
Not sure what is the best approach to follow, but I wanted to answer your question if it can help in the analysis.

**Comment by kevinpapst** [comment]
I think the best approach would be to bootstrap a tiny test image with the DATABASE_URL and see if it responds.
Not sure if it is worth the trouble though...

Thanks for sharing your findings @Not-Code, much appreciated! The modern tech-stack is just way to broad to understand every piece of the puzzle.

**Comment by Not-Code** [comment]
It is indeed a broad argument, but I feel that containerization (or kubernetes in general) is one of the best modern innovation. Even at home where is generally not possible to have a full fledged hypervisor and maybe you need to run different environments. It is also easier to distribute software to the end user that doesn't need to understand all external requirements.

Returning on the argument, it should be ok to do this. You can set the environment variable DATABASE_URL directly in the docker run command. So if in the file [docker.yml](https://github.com/kimai/kimai/blob/c5dcf9e0fd057d1167c3754858d288f004b47b2f/.github/workflows/docker.yaml) instead of:

`              run: docker run --rm --entrypoint /assets/test-lite.sh kimai/kimai2:${{ matrix.server }}-${{ matrix.type }}`

you put:

`              run: docker run --env DATABASE_URL='mysql://kimai:kimai@127.0.0.1:3306/kimai?charset=utf8mb4&serverVersion=5.7.40' --rm --entrypoint /assets/test-lite.sh kimai/kimai2:${{ matrix.server }}-${{ matrix.type }}`

that should do the trick.

**Comment by tobybatch** [comment]
The problem we have is that there is no database built into the container. Historically I could get around that and test the install by using a sqlite database but that has stopped working.

The solution is to remove the test script from the build all together and I'll write a GitHub action that builds, tests then pushes the images.

Do do this I propose that we build, tag and push an image called kimai/kimai2:head on every merge into main.

This image would build, push and test the head of the main branch, then on tagging a release it would tag latest, dev prod etc.

**Comment by kevinpapst** [comment]
We can do this, but I am pretty confident that the solution from @Not-Code could work.
Doctrine, for some weird reason, tries to open a connection ONLY IF there is not server version provided in the DATABASE_URL. But if you provide one, even if the entire connection is wrong, this does not happen.
And as the test script only calls the `kimai:version` command, which does not query the database, it might/should/could work. Can you try locally @tobybatch ? Or tell me how I can do it?

**Comment by Not-Code** [comment]
@kevinpapst the best way to test this is having a machine where a container runtime engine is installed (for development we are generally talking of docker or podman). Also it is needed that the host machine has a linux kernel. This could also be obtained in windows with a Hyper-V virtualization or a Hyper-V isolation, but I would just suggest to stuck to linux, for simplicity.

In case you have a access to a Linux distribution installing docker or podman (in case they are not preinstalled) is pretty simple.

In my case I'm running Fedora with podman but the same can be done with docker substituting the command `podman` with `docker`.

Here I test one of the images [kimai/kimai2:apache-dev] to raise the exception:

<img width="574" alt="image" src="https://github.com/kimai/kimai/assets/18069705/9d80becb-49ca-475b-a9ff-ad5b06113146">

and here I apply your fix:

<img width="1170" alt="image" src="https://github.com/kimai/kimai/assets/18069705/ca3f3604-1021-49c3-bc83-677ef98d8bc0">

From what I see it does work. Maybe some escape character will be needed in docker.yml file, but the general idea should be applicable.

**Comment by Not-Code** [comment]
Adding to the previous point I did a bit of research because the error `unable to open database file` was bugging me pointing more at an issue of permission inside the container that to sqlite itself.

After poking around a bit I can confirm that the sqlite string works when the path where the database is created has appropriate permissions.

### ERROR POINTING TO /opt/kimai/var/data

<img width="1019" alt="image" src="https://github.com/kimai/kimai/assets/18069705/c78ca402-5487-4935-85b1-08ebbbe12803">

that is having the following permissions:

<img width="625" alt="image" src="https://github.com/kimai/kimai/assets/18069705/c9162192-ea86-4699-ae99-0ef9e1b642c3">

### OK POINTING to 777 folder

<img width="836" alt="image" src="https://github.com/kimai/kimai/assets/18069705/88791f8f-b62c-4ba1-8d51-ae27032ec506">

that has 777 permissions:

<img width="509" alt="image" src="https://github.com/kimai/kimai/assets/18069705/664ae95f-00ec-49c8-85b6-9c80af915a67">

-------

So if you prefer to keep the original sqlite as a DATABASE_URL that is still possible. And this, from what I understand, will revert the situation to the previous status.

Now, to do that is enough to specificy the DATABASE_URL during the docker run like I did above pointing to the current directory (/var/www/html) or looking at the permission issue in /opt/kimai/var/data and fix that in the script/Dockerfile etc...
There are many different ways to fix permission (even running the container with another user) but you should get the basic idea at this point. Hopes this helps.

**Comment by kevinpapst** [comment]
Excellent debugging skills 👍  Kimai needs more people like you 😄

**Comment by kevinpapst** [comment]
Fixed in #4541
