### ISSUE TITLE
PDO SQLite installation fails

### ISSUE THREAD

**Issue by tonjo** [kimai/kimai#456]
Error when selecting PDO and sqlite as backend:

`Fatal error: Call to a member function execute() on a non-object in [...]/kimai/installer/steps/60_db_select_pdo.php on line 36`

The problem is:
`$pdo_query = $pdo_conn->prepare("SHOW DATABASES;");`

SQLite does not have `SHOW DATABASES` command.

In addition, SQLite installation should not ask for host, user and password.

**Comment by ServiusHack** [comment]
We dropped support for PDO and therefore anything except MySQL in 0.9.3. Support for different database backends might come back later when we switch to the new API and Doctrine.

I won't fix this for 0.9.2 because what little time I have will be invested in the next release and the new API. Hope you understand that and have the option to use MySQL.

**Comment by tonjo** [comment]
Oh, Pity ;)
Of course I understand, I switched to MySQL.
