### ISSUE TITLE
Wrong calculation for amounts with decimals

### ISSUE THREAD

**Issue by xstable** [kimai/kimai#4581]
### Describe the issue

In the screenshot below you see some timetracks. 
The Project is configured like this: 

Internal Price 50,00 EUR
External Price 65,00 EUR

In the screenshot you see, that if the time-amount has decimals (e.g. 0.73 or 0,08 or 0,68) the calculated sum is wrong.

**Example:** 
0.73 * 50 = 36.50  (Kimai = 36,67)
0.73 * 65 = 47.45  (Kimai = 47,67)

Why does this happend? Is this some kind of rounding difference?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.10.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Screenshots

![image](https://github.com/kimai/kimai/assets/1778068/c4735215-5afc-4deb-a797-53929a881313)

**Comment by kevinpapst** [comment]
Kimai does not use the displayed decimal duration you see there. 
The real number is likely something like 0,7334.
Kimai calculates the cost for each timesheet in the moment it is stopped.

You cannot transfer every timesheet duration (minutes = base 60) to money (currency = base 100).

You have to 
1. use rounded times if you want to prevent that
2. or displayed time instead of decimal duration

Best is to round duration to 15 minutes, then you will never see such a rounding issue.
