### ISSUE TITLE
Your mounts are not valid...

### ISSUE THREAD

**Issue by mastertIT** [kimai/kimai#4629]
I asked a question about how local.yaml is made persistent and I received rude answers from you. I'm not asking for free support I'm simply asking a legitimate question.

**Comment by kevinpapst** [comment]
Holy moly.

No. You are causing errors due to wrong usage and upon given options that might fix it, you don't test the solution.
You keep on arguing and wasting precious time.

There is never a step 2 before step 1. 

You still did not provide an answer to the question if it works or not with the given mount points.
Instead you complain again instead of concentrating on the technical part ... what is your plan here? Get blocked?

> I'm not asking for free support

Do you read what you write?
