### ISSUE TITLE
raise contrast in dark mode

### ISSUE THREAD

**Issue by derStephan** [kimai/kimai#4854]
### Describe the issue

In dark mode, the arrows of time drop downs are barely visible. Is it possible to have the same color as the arrows of customers, projects and activities? 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.16.1

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

my times:
![grafik](https://github.com/kimai/kimai/assets/7764931/ceb5379c-d206-4931-89e5-660392cfe8ac)

weekly hours:
![grafik](https://github.com/kimai/kimai/assets/7764931/b428b9ac-42eb-4698-b14f-b6278af43d68)

**Comment by p-rogalski** [comment]
A lot of components are affected, not only dropdowns. See e.g. the "Preferences" tabs:

![grafik](https://github.com/kimai/kimai/assets/102597634/093b3e86-535d-41e7-b169-b130a99a3ec1)

or table headers

![grafik](https://github.com/kimai/kimai/assets/102597634/464b9a31-9738-45c5-a42a-88f80b542e6d)

etc.

**Comment by sharky98** [comment]
I think Kimai uses Tabler Core default theme "as-is", so that contrast issue is not really with Kimai.

https://github.com/kimai/kimai/blob/93ca983e0bd238e63088fd21a250531625bac381/assets/sass/_app.scss#L10-L12

However, I think the color value used is the variable `--tblr-muted`. So maybe Kimai could overwrite it in the file [assets/sass/theme-dark.scss](https://github.com/kimai/kimai/blob/93ca983e0bd238e63088fd21a250531625bac381/assets/sass/theme-dark.scss)?

**Comment by derStephan** [comment]
Thanks for the insight. I just set it in custom css plugin like that:

```
[data-bs-theme=dark]
{
    /*fix for light grey arrows and table headings*/
    --tblr-muted:#d9dcdf;
}
```
