### ISSUE TITLE
The create time entry workflow is unnecessarily verbose (on the wire)

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4870]
### Describe the problem

I have tried test-running Kimai with several staff on our team and this is feedback that has so far affected two people, both in Asia.

A team member clicked the open the dialog to start time tracking and it took 10+ seconds to open. In one instance it took over 30 seconds. This has happened multiple times for multiple people.

I am not sure how bugs/features are classified in this project. But if this continues, we will not be able to use Kimai, my staff would not accept it.

This issue addresses just the part of this issue that is not specific to Kimai Cloud. (See other issue https://github.com/kimai/kimai/issues/4869)

### Describe the solution you'd like

When clicking the "Start time tracking button" (the most important button in the application), the communication with the server should be minimal or implicit.

MINIMAL

The server response is JSON and includes only the needed data.

IMPLICIT

No request is sent to the server. The box opens immediately.

### Describe alternatives you've considered

In the future (version 3 or 4?) the entire application only receives data from the server using channel subscriptions. This means if a customer is logged in, all their browsers/devices are synchronized (like Gmail), data flow is minimized, and capacity of the server is maximized.

### Screenshots

This screenshot is from a fast connection in USA.

![slow](https://github.com/kimai/kimai/assets/382183/f5f98bd7-ff81-4507-8131-e6ff09402572)

Comparing it to another request on the same server you can see how much more work the server is doing:

![Screenshot 2024-05-20 at 12 10 09](https://github.com/kimai/kimai/assets/382183/e2105cad-7ed5-4679-912e-88d8fa441629)

---

The "start time tracking" dialog box is especially slow for our workers in Asia. And we see times of up to 30+ seconds to load that dialog. 

We cannot attribute all of this slowness to Kimai or Kimai Cloud. Especially when I am also running a Google Meet with them at the same time (which uses a lot of internet bandwidth). But it did help us to identify the problems that maybe other people are seeing too.

**Comment by kevinpapst** [comment]
Kimai Cloud is hosted in EU. Customers from e.g. Africa, US and South America have never mentioned anything remotely comparable. 10s+ is insane and the servers are bored.

Not sure what your screenshots should tell me. The first one shows you that the cloud needs approx. 230ms to render the page. Which is not the fastest, but okay. The second screenshots is a tiny static image. The 350ms download time is likely caused by the fact that we are on different continents and such connections sometimes lag (not 10+ seconds though).

I did this right now and got repeatable results of less than 250ms for the answer, which is totally acceptable:
<img width="1338" alt="Bildschirmfoto 2024-05-20 um 18 58 01" src="https://github.com/kimai/kimai/assets/533162/db182f9b-b908-4603-98b2-32675d55009f">

The Trial clouds shares a rather small connection pool, so if many people test at the same time, they might have to wait a few ms. That is to prevent certain usage abuses I have seen in the past with the Trial clouds.  Sorry if it hits you as legit interested Trial user.

If the issues persist for your asian colleagues, I am certain there are competitors that utilize asian data-centers, which I don't right now. I do understand your complaints and I wouldn't use a system, with such lagging myself. But I don't think I can do anything about it, because I am pretty certain that this is not caused by the cloud itself. If you are interested in further technical talks, please use support@kimai.cloud. This repository is about the core software and not for discussing the IT behind the cloud.
