### ISSUE TITLE
Two minute difference in time tracking

### ISSUE THREAD

**Issue by fulldecent** [kimai/kimai#4889]
### Describe the problem

Our team is testing Kimai and here is some of the feedback we got compared to another software we are currently using.

They are seeing that Kimai is counting two less minutes that other software.

### Describe the solution you'd like

The time in the menubar updates more frequently to show the actual time.

Our team is very concerned that the time tracking will accurately count the time they are working.

Probably a menubar app, #4888, will be the most accurate.

### Screenshots

![diff](https://github.com/kimai/kimai/assets/382183/d4f02bce-dc64-477c-9dee-de4cd690462c)

**Comment by kevinpapst** [comment]
Point 5 is invalid, there are many places where you can see the aggreagated time, e.g. on the dashoard and you can turn it on for "my times" as well (through a user preference).

All the other point clearly sounds as if you are looking for another software.
Kimai will NEVER ship idle detection or screenshot support.

Kimai tracks by second, so there is no chance that times get lost.

**Comment by fulldecent** [comment]
I am not claiming the time is lost.

But the time that is shown in the tab title is not updating as fast as the other time.

This is causing the staff to think that the timer is running slow.

**Comment by fulldecent** [comment]
Here is the experience that our staff is seeing.

![Screenshot 2024-06-02 at 09 04 43](https://github.com/kimai/kimai/assets/382183/7fa7f9e1-fc9d-4acc-b99d-364c2b2f6c0e)

**Comment by kevinpapst** [comment]
Probably happening because the browser is slowing down or even hibernating activity in background/inactive tabs. 

Not sure if there is a setting to prevent that.
Might be less important once you only use one tracker.

Not sure what is described there, but time does NOT get lost.
Kimai starts/stops immediately when the request hits the server. 

Also check your rounding rules. 
Seconds get cut off by default, so if you round up on start and round down on end, this could lead to 2 minutes.
