### ISSUE TITLE
Show/export list of currently working users

### ISSUE THREAD

**Issue by natanoj** [kimai/kimai#609]
We are looking for an alternative to keep track of currently working employees and volunteers. We are required by law to keep track of who are currently working for us, and where they are physically located.

I have tried out Kimai just briefly but have not found an easy way to get a list of currently clocked in users, is this possible? We need to be able to quickly export a list of people currently working (i.e. name, present location, social security number etc) when requested by the authorities. If this is not possible, consider this a feature request :)

Background information:
This is required by Swedish law for organisations contracting building workers of any kind since 2016-01-01.

**Comment by kevinpapst** [comment]
Hey natanoj, finding all currently working users is fairly simple (not out-of-the-box but possible), but Kimai does not yet offer any solution to store extensive user data.
Are you using Kimai already for time tracking? How important is that feature for you? I am just asking because this is not a feature that is commonly requested ... in reality its the first time someone asks for it. So I am wondering if you need it for your business right away or are you currently evaluating time tracking software?

**Comment by natanoj** [comment]
Currently I am evaluating alternatives for keeping track of currently working users. The most important feature is to get a list of currently working users and where they are physically located (we can use the project for that). Extensive user information is not important I think. We are not using any other time tracking software at the moment. Kimai is evaluated as an alternative to commercial offerings here in Sweden. 

We will be needing this feature before summer, when work regulated by this new law will begin. 

Kevin Papst <notifications@github.com> skrev: (8 mars 2016 23:09:53 CET)
>Hey natanoj, finding all currently working users is fairly simple (not
>out-of-the-box but possible), but Kimai does not yet offer any solution
>to store extensive user data.
>Are you using Kimai already for time tracking? How important is that
>feature for you? I am just asking because this is not a feature that is
>commonly requested ... in reality its the first time someone asks for
>it. So I am wondering if you need it for your business right away or
>are you currently evaluating time tracking software?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kimai/kimai/issues/609#issuecomment-193988602

-- 
Jonatan Åkerlind 
+46702002897

**Comment by kevinpapst** [comment]
So, you basically need a table including:
list of currently working users, project + location, task, customer
?

**Comment by natanoj** [comment]
That would cover it I believe. 

Kevin Papst <notifications@github.com> skrev: (8 mars 2016 23:22:29 CET)
>So, you basically need a table including:
>list of currently working users, project + location, task, customer
>?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kimai/kimai/issues/609#issuecomment-193995854

-- 
Jonatan Åkerlind 
+46702002897

**Comment by kevinpapst** [comment]
Well, sounds do-able. But as this is a very special request, it wont be high rated on our feature request list, unless more people vote for it.
If you need it asap, there is always the option to sponsor development of new features.

**Comment by piflixe** [comment]
Hi there,

I just wanted to add that many companies have new regulatory 
requirements that would need a feature like that. As far as I can see, 
the majority just uses a login with a member card at the front door 
(since someone could already work in the workshop and forget to login 
into kimai). So I would suggest the following:
- including the "who is working" table into kimai in the short to middle 
term
- configuring the API in a way that a login device at the front door 
could trigger the table (longterm)

As far as I know, the regulatory requirements target the company to be 
able to know who is in the building. When kimai is used as a true web 
service, this does not solve the problem since people could be logged in 
from outside the premises.

I would still vote for the feature, since it also a nice-to-have for 
admins when trying to figure out if maintenance is possible at the 
moment. And for a CEO or controller it might also be a nice feature.

Regards,
Felix

-- 
Felix Piela
August & Piela Konstruktiv GbR
Tempelhofer Weg 11-12
10829 Berlin
Tel. 030 9190 5511
mobil 01523 193 7441
Fax 030 9190 973
www.konstruktiv-berlin.de

Am 08.03.2016 um 23:32 schrieb Kevin Papst:

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
