### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by VBScab** [kimai/kimai#702]
Let me say, straight off the bat, that I am NOT a database expert. What I have learned over the years, however, is to use normalisation wherever possible. From my (admittedly so far limited) experience today, it seems that the Kimai database is not normalised.

To paraphrase for the sake of brevity, the idea of normalisation is to have data entered only once. To wit...

Having edited an activity rate for one of the users, I noticed that the timesheet entry for that user's activity didn't change when I re-opened the 'Timesheet' view. That's because, rather than looking up the rate in the appropriate table and adding the rate index into the timesheet record, it has been "hard-coded" with the old rate's actual value. This means that, if I were using this for real work and a user's rate had been wrongly entered, I'd have to go through every entry for that user and update the relevant records. Yes, I could do that in a SQL query but how much simpler it would be if all I had to do was edit the rate to its correct value!

**Comment by kevinpapst** [comment]
Let me start by saying that the rates are currently rewritten, as they are broken by design.
Nevertheless, Kimai will always store the rate for one time entry exclusively with this entry.
Just think about a changing rates within a project, a freelancer working for multiple customers with different rates and so on...
That is not a question of normalization, but a question on how Kimai works. The decision was made on purpose and not because of a bad database design.
