### ISSUE TITLE
How to use autologin with kimai

### ISSUE THREAD

**Issue by kimamobo** [kimai/kimai#750]
As far as i understood it is possible to autologin to an account in kimai. But i simply not able to figure out how.

I would like just to start without needing to enter credentials. 

I'am using Kimai on my home server just for my own needs.

Can someone guide me?

Thanks!

**Comment by simonschaufi** [comment]
> As far as i understood it is possible to autologin to an account in kimai. But i simply not able to figure out how.

There are several different authentication providers available, I think the one that fits your needs is HTTP Auth.

> I would like just to start without needing to enter credentials.

This is not possible since kimai needs to know which user it should autologin even if there is just only one.

Of course you can also write your own authentication provider and authenticate admin user. I have looked at the documentation which is not complete at all but I hope you find it at least a bit helpful. If you are successful, we would highly appreciate it if you could improve our documentation.

**Comment by kimamobo** [comment]
To be honest: i'am still stuck with this issue.

My idea was to have a favorite link in my browser bookmarks like:

http://adminusername:adminuserpasswort@127.0.0.1/kimai/index.php

As far as i understood: with the http auth this can be done. If this is correct: i'am still not able to set this up.

Any help or tipp is appreciated!

Thanks!

**Comment by simonschaufi** [comment]
I just tried it myself. 

1. download develop branch
2. create .htaccess

```
AuthType Basic
AuthName "kimai"
AuthUserFile  /absolute/path/to/.htpasswd
Require valid-user
```
3. [Create .htpasswd file](http://www.htaccesstools.com/htpasswd-generator/)
4. Login with ``http://admin:changeme@kimai.localhost/index.php``
