### ISSUE TITLE
Config to hide Amount/Lohn column

### ISSUE THREAD

**Issue by kevinpapst** [kimai/kimai#80]
It would be good to have either a per user setting to hide a table column (here Amoun/Lohn) or the capability to hide it on the fly via double-click.

In some circumstaces (e.g. working at a customers place with other co-worker) you do not want to see that column on your screen.

**Comment by izrunas** [comment]
The hide option should be both user-controlled and admin-controlled.  There are also use-scenarios where some employers using Kimai may not want employees to see billing rate at all (this is more for when Kimai is used to track internal labor costs instead of billing rates (since most salaried employees are not supposed to know the salaries of other staff, etc.).

**Comment by plessmann** [comment]
I aggree. This seems to be an old topic but nothing happend around this?

**Comment by plessmann** [comment]
Okay. I implemented this feature and created a pull request to add this functionality for the next release:
@see https://github.com/kimai/kimai/pull/512

**Comment by kevinpapst** [comment]
Archiving old issues. [Please switch to Kimai 2](https://github.com/kevinpapst/kimai2)...
