### ISSUE TITLE
Something wrong with cyrillic symbols in exported pdf

### ISSUE THREAD

**Issue by murmuringvoices** [kimai/kimai#801]
There is something wrong with cyrillic in exported pdf

<img width="793" alt="screen shot 2016-08-23 at 20 13 50" src="https://cloud.githubusercontent.com/assets/14987450/17901990/28834fd6-696e-11e6-839a-7fdddc41cafa.png">
#### Steps to reproduce
1. Use any cyrillic symbols in nicknames/projects/customers/anywhere
2. Export PDF via "Export" tab
#### Reproducable on demo.kimai.org? [yes|no]

Yes, easily reproducable
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]

github develop

**Comment by simonschaufi** [comment]
I think this would be fixed with the following PR: #794 In the meantime you can change your db to utf8 and try it on your own (apply the PR).

**Comment by kevinpapst** [comment]
I tried it locally. My database is completely utf8 and the russian text is correct in the database:
nevertheless, the PDF is displaying the invalid encoding. 
So yes, Bug confirmed.

**Comment by kevinpapst** [comment]
Hey @murmuringvoices, 
I guess I found the problem: seems the font we used previously (helvetica) has problems with cyrillic characters.
Can you please test the changes from the linked pull request and let us know, if that works for you.

**Comment by murmuringvoices** [comment]
@kevinpapst Everything is ok now with cyrillic characters, but as far as I can see - freesans does not support russian ruble currency symbol - ₽
Maybe it's possible to find some font which will support it too?
And thank you for the solution!

**Comment by kevinpapst** [comment]
LOL, especially the Rubel sign not? Then why not calculate in Kopeka? ;-) 
Probably its better than before, but still not a solution we can use - the currency is pretty important on invoices and exports...

Okay, I will read a little more and see if I can find something. 
You could help as well and ask Yandex too. Probably such problems are more discussed in the russian part of the internt, which I hardly read. 
We need the Font in combination with the PHP Library "TCPDF".

**Comment by kevinpapst** [comment]
I played around some time, but could not find a proper solution, that will work out of the box.
What you can do:

- Download or create a TTF font file including the Ruble sign and save it at **/tmp/myfont.ttf**
- Go to your command line and change to directory: **kimai/libraries/tecnickcom/tcpdf/tools/**
- Execute: **php tcpdf_addfont.php -b -t TrueTypeUnicode -i /tmp/myfont.ttf**
- Open the file **kimai/extensions/ki_export/export_pdf.php** and replace all occurences of 
**$this->SetFont('freesans'** with **$this->SetFont('myfont'**

That should do the trick for you. I just could not find a open source compatible ttf file that we can include. Otherwise I would have done that.
