### ISSUE TITLE
how to setup group roles for supervision

### ISSUE THREAD

**Issue by piflixe** [kimai/kimai#818]
I am trying to set up group roles for a supervisor, who is a client's employee. Our usecase is that a project manager from our client wants to be able to see how much time was already spent and so on. This User should
- see other users in the project (and group), but not all users on kimai
- see projects of the customer (his employer)
- see all time entries for the customer (his employer)
- should not be able to create own entries (since his workload should not appear in our invoices)

I am confused because in the group role settings, there is no "view" checkbox as in the global role settings. But on the other hand, in global role settings, I can only edit "view" checkboxes for "other groups.

As I understand, the desired functionality would be possible if I setup one group for each project, then add the group to all activities and then create different group roles. Since we work with the same team (except for the supervisors) all the time on a great number project with a great number of activities, this solution would create a huge overhead and hence is not practical.

I hope someone else can understand the usecase and the problem. I would really appreciate any tips on the role settings and setup.

I am using kimai 1.1.0.1389 github master branch.

**Comment by simonschaufi** [comment]
I think that is what the password for the customer is for. With the customer name as username and his password he can see exactly what you want (with one bug: the project list is empty)

- [x] see other users in the project (and group), but not all users on kimai
- [ ] see projects of the customer (his employer)
- [x] see all time entries for the customer (his employer)
- [x] should not be able to create own entries (since his workload should not appear in our invoices)
