### ISSUE TITLE
Max lines for HTML invoices

### ISSUE THREAD

**Issue by MisterChoc** [kimai/kimai#847]
Hallo zusammen, 

ich habe ein Problem mit dem Seitenumbruch bei einem HTML "Leistungsnachweis", dafür habe ich den Projektbericht etwas verändert. Anstatt des Projekttitels wird das Kommentar für den Zeiteintrag angezeigt. Ab einer gewissen Anzahl von Einträgen zerschießt er den Bericht und wechseln nicht auf eine neue Seite.. gibt er hierzu irgendeine Lösung? 
<img width="824" alt="bildschirmfoto 2016-09-30 um 13 03 06" src="https://cloud.githubusercontent.com/assets/20971537/19020185/85cec6d2-88a1-11e6-9ecb-85ac53efd800.png">

**Comment by kevinpapst** [comment]
I couldn't find a suitable solution, which works properly for multiple situations:
- invoices with a lot of entries and/or only a few entries
- invoices that have a page split inside

I can tell which CSS you need to adjust to see the table properly, but that might still break the print layout...

**Comment by Marcel-Reis** [comment]
Why is the shown page such short? Is it not possible to show the complete invoice on the side and when you print it the page will be divide automatically with the head and footer?

**Comment by kevinpapst** [comment]
If there is someone with more frontend know how, I would love to fix that issue!
But my HTML & CSS skills are not sufficient, sorry!

I don't think that there is a good HTML solution for longer invoices with multiple pages.

**Comment by simonschaufi** [comment]
I have never used HTML as I love the odt files. There you don't have any limitations.

**Comment by paulolindoso** [comment]
Hi Kevin,
Can you point me the CSS that needs adjusting?
I want to use HTML templates for invoicing, but am facing the same problem...
My frontend skills are not brilliant, but I think they'd be enough to tackle the problem...! :)

**Comment by kevinpapst** [comment]
Are you sure? If you cannot find the CSS, I am not convinced that it is enough ^^ 
What about printing an invoice and then checking the source code of the result page?

Okay, jokes aside ;-)

I cannot say which template you use, so these are my hints: https://github.com/kimai/kimai/blob/master/extensions/ki_invoice/invoices/freelancer/style.css
https://github.com/kimai/kimai/blob/master/extensions/ki_invoice/invoices/my_company/style.css

**Comment by MisterChoc** [comment]
any news? i use kimai for time recording und export on the end of the month the timesheed (freelancer) that works perfekt - only the issue with the time lines is a pain - please can you help? i think that is also intresting for many other peoples...

**Comment by Marcel-Reis** [comment]
No not jet. They told me that there will be a new version from kimai in a few month. Maybe it's working with the new one

**Comment by MisterChoc** [comment]
i've tested it with the new version - same issue :(

**Comment by Marcel-Reis** [comment]
A complete new kimai version.

**Comment by MisterChoc** [comment]
i've tested it wit the kimai v2 version - same issue (i think that is the new version) https://v2.kimai.org/

**Comment by Marcel-Reis** [comment]
Oh ok 😞 I hoped they fix it. I also tried to pay for this change but Simon had no time to fix it.

**Comment by kevinpapst** [comment]
@MisterChoc thats interesting. On the official demo-v2 page long invoices split properly between multiple pages on my machine (using Chrome): https://demo-v2.kimai.org/en/invoice/?template=1&user=6&begin=2011-06-03&end=2018-06-30&customer=2
But we are not talking about v2 here...

The problem is easy to fix, remove the absolute height of the print page and reposition the footer. But the next thing that will happen: someone will open a new issue and complain that short invoices look shitty. Thats what I was talking about: my frontend skills are not good enough to fix it for all use-cases.

But for creating long invoices, it should be enough to remove these 2 lines:
https://github.com/kimai/kimai/blob/master/extensions/ki_invoice/invoices/my_company/style.css#L77
https://github.com/kimai/kimai/blob/master/extensions/ki_invoice/invoices/my_company/style.css#L246

And the other template, again remove these lines:
https://github.com/kimai/kimai/blob/master/extensions/ki_invoice/invoices/freelancer/style.css#L74
https://github.com/kimai/kimai/blob/master/extensions/ki_invoice/invoices/freelancer/style.css#L225

**Comment by simonschaufi** [comment]
Maybe with flex layout we can solve it.

**Comment by Marcel-Reis** [comment]
@kevinpapst i tried now to delete the two lines
(
https://github.com/kimai/kimai/blob/master/extensions/ki_invoice/invoices/my_company/style.css#L77
https://github.com/kimai/kimai/blob/master/extensions/ki_invoice/invoices/my_company/style.css#L246
)

and it is working with Google Chrome Version 67.0.3396.99 (Offizieller Build) (64-Bit)

Thank you!

**Comment by kevinpapst** [comment]
Kimai 1 is not maintained any longer.
This issue will now be closed.
Please [read more about Kimai 2 here](https://github.com/kimai/kimai/issues/1291).
