### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by anchev** [kimai/kimai#939]
#### Expected behaviour

The UI should be stable, like this:

https://snag.gy/sRrOtu.jpg

#### Actual behaviour

The UI is unstable. Elements hide and/or distort (change size) when the user interacts with the UI, HTTP messages appear inside interface. Example of the distortion happening after stopping recording of an activity:

https://snag.gy/sVebh6.jpg

#### Steps to reproduce

Hit the Play button, then stop recording. Sometimes you don't even need to click 'stop' to see the bug. The workaround is to hit F5 to refresh however sometimes a few F5's are necessary.

Another scenario: click the pencil to edit a recorded activity - the activities for the project are not visible and clicking OK results in an error:

https://snag.gy/8WuABT.jpg

To work around this one needs to click back and forth on other projects until the activities for the project appear.

#### Reproducable on demo.kimai.org? [yes|no]

Yes - I could reproduce the hiding of UI elements. When I start recording the lines in the timesheet disappear:

https://snag.gy/jENpyh.jpg

Then I stop recording, still empty timesheet:

https://snag.gy/vM1LFb.jpg

Then I hit F5 and only then the interface looks right:

https://snag.gy/lqUHyn.jpg

#### Kimai version

1.1.0.1389 but this has been around since older versions.

**Comment by simonschaufi** [comment]
I cannot reproduce this, neither on demo.kimai.org nor on my own kimai installation.

**Comment by anchev** [comment]
I am using chromium-57.0.2987.98-105.2.x86_64 on openSUSE Leap 42.2

**Comment by simonschaufi** [comment]
Can you check with another browser?
Just tested with Chrome 57.0.3000.0 and works perfectly on windows.

**Comment by anchev** [comment]
Chromium != Google Chrome

Just tested with MozillaFirefox-52.0.1-57.3.1.x86_64:

The problem with resizing/showing-http-info doesn't appear however when I pres Play a new line in the time sheet doesn't appear (not always) although recording starts. Also the Stop button is gray (disabled) and I have to refresh the page in order to make it usable (red).

Also tested with google-chrome-stable-57.0.2987.110-1.x86_64:

After a few quick play/stop/play/stop everything seemed to work fine until I pressed the pencil for one of the recorded actions, then the element of that line got messed up like on the second link. Just for your info: I tested with this same browser http://acid3.acidtests.org/ and I get 100/100

**Comment by anchev** [comment]
The problem still remains on latest versions of FF and Chromium on Linux.

I wonder if that may be somehow related to the vhost configuration and the fact that I am running kimai on a different port (not 80), i.e. if the XHR requests may be messing up something with the interface on response. Here is my apache vhost config:

https://goo.gl/Sm59we

The exact same config but for different vhosts works flawlessly.

Can you please help to investigate the problem? This interface glitch is really annoying. I have to refresh several times after each click on kimai's interface.

**Comment by anchev** [comment]
More info (just found):

Running tail -f on the master error log of Apache shows this on each press of kimai's play/stop button:

```
[Fri May 12 14:35:40.333866 2017] [core:notice] [pid 17240] AH00052: child pid 18150 exit signal Segmentation fault (11)
[Fri May 12 14:35:40.333890 2017] [core:notice] [pid 17240] AH00052: child pid 18151 exit signal Segmentation fault (11)
[Fri May 12 14:35:41.334941 2017] [core:notice] [pid 17240] AH00052: child pid 18152 exit signal Segmentation fault (11)
```
The first 2 lines appear on pressing play, the last one on pressing stop.

**Comment by simonschaufi** [comment]
Can you check the browser console with F12 please? I think this is a bit more helpful than child pid exits. Do you get correct 200 status code?

**Comment by anchev** [comment]
Sure.

After reading your last post I pressed 'play', all was HTTP 200. Then I pressed the stop button and I got 404 for URL path like this:

`/skins/standard%17%03%03%01q%EF%BF%BD%EF%BF%BDQB%D6%98s%0F%EF%BF%BD-%EF%BF%BD`

Then I pressed 'play' gain. On the second press of the 'stop' I got HTTP 400 for this URL path:

`/skins/s%17%03%03%01q%EF%BF%BD%EF%BF%BDzWj%EF%BF%BD%EF%BF%BD%15%EF%BF%BD%CD%AFz%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%08%7B)s%1A%EF%BF%BDAo%EF%BF%BD%EF%BF%BD%EF%BF%BDn%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%1AQ%EF%BF%BD%EF%BF%BD[%EF%BF%BDZRBn%16%EF%BF%BDf%EF%BF%BDZSw%EF%BF%BD%EF%BF%BD%05D%10%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BDh%EF%BF%BD%EF%BF%BDx%EF%BF%BD&JE%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BDY%EF%BF%BDy%EF%BF%BDNl1f+,YE%EF%BF%BD%05Xn%0B%EF%BF%BD0%EF%BF%BDP;%EF%BF%BDj,%01%EF%BF%BD%EF%BF%BD%%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BDj%EF%BF%BDMy%EF%BF%BDZ%EF%BF%BD7%EF%BF%BD%EF%BF%BD%EF%BF%BD?{%16%EF%BF%BD%20%7F%EF%BF%BDk2!%EF%BF%BD:.%EF%BF%BD4%EF%BF%BD%DE%98R`%EF%BF%BDo%EF%BF%BD^D%EF%BF%BD%EF%BF%BD*%1A%0C%DF%9F%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD[]T&%06%EF%BF%BD%EF%BF%BD%EF%BF%BDD%25EF%25BF%25BD%25%25EF%25BF%25BD%25EF%25BF%25BD%25EF%25BF%25BD%25EF%25BF%25BDj%25EF%25BF%25BDMy%25EF%25BF%25BDZ%25EF%25BF%25BD7%25EF%25BF%25BD%25EF%25BF%25BD%25EF%25BF%25BD%3F%7B%2516%25EF%25BF%25BD%2520%257F%25EF%25BF%25BDk2!%25EF%25BF%25BD%3A.%25EF%25BF%25BD4%25EF%25BF%25BD%25DE%2598R%60%25EF%25BF%25BDo%25EF%25BF%25BD%5ED%25EF%25BF%25BD%25EF%25BF%25BD*%251A%250C%25DF%259F%25EF%25BF%25BD%25EF%25BF%25BD%25EF%25BF%25BD%25EF%25BF%25BD%25EF%25BF%25BD%25EF%25BF%25BD%5B%5DT%26%2506%25EF%25BF%25BD%25EF%25BF%25BD%25EF%25BF%25BD
`

But the UI glitch happens even when everything is HTTP 200.

**Comment by anchev** [comment]
I think I may have found the issue... After trying to delete a few entries from the timesheet I got a few "permission denied" popup dialog boxes. So after some digging I decided to disable mod_security and now I don't see segmentation faults in log and the interface seems stable for the moment. Perhaps mod_security may have been limiting some part of the requests?

I will keep an eye on it and write again if this didn't help. Thank you for your time.

**Comment by simonschaufi** [comment]
I wonder where these strange looking URLs come from.
It would be great if you could figure out if that module is the main cause. Then we can either fix it or (if possible) check if the module is active and let the user know that kimai won't work with it.

**Comment by timlegge** [comment]
I've used mod_security in the past.  It should be possible to configure it with rules that would allow it to work.  If I get a minute I will take a look

**Comment by anchev** [comment]
@simonschaufi - it seems that mod_security was the issue because I no longer experience the UI glitches after disabling it and the segmentation faults disappeared for good. However I am not really familiar with the intricacies and configuration of that module so I cannot provide any detailed testing in order to find out what exactly is creating the weird URLs etc. I haven't ever configured anything for mod_security so it should be using its default settings (whatever that may mean), so perhaps if you can install the module you can test and hopefully find out what may be causing the trouble.

I can speculate though: it seems kimai is sending a few XHR requests quickly on play/stop button press and it may be a case of mod_security filtering/limiting the rate of requests which may lead to strange packets flying back and forth. Afaik AH00052 segfaults are caused by software trying to access memory for which it has no permission.

**Comment by simonschaufi** [comment]
Thank you @timlegge 
I'm just creating my own vagrantfile so that i can easily create testcases with different server configurations.

**Comment by timlegge** [comment]
So with mod_security..

there are two log files usually in the apache2 log directory but it could be anywhere.  They are modsec_audit and modsec_debug.

tail those files and watch for logged issues as mod security finds suspicious content.  Yoiu will see something containing:

`[12/May/2017:21:29:47 --0300] [kimai-dev.local/sid#7f5ec9f4fe58][rid#7f5ebc6800a0][/extensions/ki_export/processor.php][1] Access denied with code 403 (phase 2). Pattern match "\\%((?!$|\\W)|[0-9a-fA-F]{2}|u[0-9a-fA-F]{4})" at ARGS:dateformat. [file "/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_20_protocol_violations.conf"] [line "465"] [id "950109"] [rev "2"] [msg "Multiple URL Encoding Detected"] [severity "WARNING"] [ver "OWASP_CRS/2.2.9"] [maturity "6"] [accuracy "8"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/EVASION"]
`
The id and msg may be different...

If you believe them to be false positives (normal behavoiur of the web application - you are not being attacked) you can create a custom rule to address it.

Locate the section of the apache config where your rules are called.  for example in /etc/apache2/mods-enabled/security2.conf:

```
Include "/usr/share/modsecurity-crs/*.conf"
Include "/usr/share/modsecurity-crs/activated_rules/*.conf"
```
Add somthing like this after the other rules have been included:

`Include "/usr/share/modsecurity-crs/custom_rules/*.conf"
`

Create the /usr/share/modsecurity-crs/custom_rules directory and create a kimai.conf file

for the rule above you can add:

`SecRuleRemoveById 950109`

Restart the web server after saving the file and that rule will not be used.  

However, as you say mod_security is a complex beast so that line above disables that rule everywhere.

Something like this would be more targeted and likely protect you better:
`
SecRuleUpdateTargetById 950109 "!ARGS:dateformat"
`
The log above showed that the match was on the dateformat parameter.

I have not had to do much with mod_security in awhile so I needed a refresher.  There is an excellent page at https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/.  There is even some information about a script there that will combine a false positive rule if and URL to suggest an exclusion rule.

It would likely be best to start logically on a test system and enable one rule file at a time, surf or crawl the site and start creating the rules you need.

If I get time I will try to come up with a set of exclusions required for mod security cabed on the owasp core rules but different rules versions will have different needs.

**Comment by timlegge** [comment]
Crawl means just that, don't run an attack tool and start excluding those events

**Comment by timlegge** [comment]
SO, here is a set of custom rules based on the 2.2.29 cure rule installed by Ubuntu in 16.04 with most of the base rules in enforcing mode:

SecRuleUpdateTargetById 950109 "!ARGS:dateformat"
SecRuleUpdateTargetById 950109 "!ARGS:table_time_format"
SecRuleUpdateTargetById 950109 "!ARGS:date_format_1"
SecRuleUpdateTargetById 950109 "!ARGS:date_format_2"
SecRuleUpdateTargetById 981319 "!ARGS:axValue"
SecRuleUpdateTargetById 981173 "!ARGS:axValue"
SecRuleUpdateTargetById 981319 "!ARGS:SAMLResponse"
SecRuleUpdateTargetById 981243 "!ARGS:SAMLResponse"
SecRuleUpdateTargetById 973302 "!ARGS:SAMLResponse"

Note that SAMLResponse is only required in my Devel version that has SAML support.

**Comment by timlegge** [comment]
Couple of more

```
SecRuleUpdateTargetById 950109 "!ARGS:dateformat"
SecRuleUpdateTargetById 950109 "!ARGS:table_time_format"
SecRuleUpdateTargetById 950109 "!ARGS:date_format_1"
SecRuleUpdateTargetById 950109 "!ARGS:date_format_2"
SecRuleUpdateTargetById 981319 "!ARGS:axValue"
SecRuleUpdateTargetById 981173 "!ARGS:axValue"
SecRuleUpdateTargetById 981173 "!ARGS:axColumns"
SecRuleUpdateTargetById 981318 "!ARGS:quote_char"
SecRuleUpdateTargetById 981242 "!ARGS:quote_char"
SecRuleUpdateTargetById 981319 "!ARGS:SAMLResponse"
SecRuleUpdateTargetById 981243 "!ARGS:SAMLResponse"
SecRuleUpdateTargetById 973302 "!ARGS:SAMLResponse"
```

**Comment by simonschaufi** [comment]
Do you think these rules are worth mentioning in the documentation?

**Comment by timlegge** [comment]
Probably.  I can write up something.  If anyone is running kimai on a
public web server running modsecurity would definitely help keep it safe.

**Comment by anchev** [comment]
Where do the IDs come from? Isn't it too system-specific to have such fixed numbers in a recommended config?

**Comment by timlegge** [comment]
The Id's come from the mod_security core rule set as delivered by OWASP.  version 2.2.29 to be exact which is the version in my Ubuntu 16.04 package.

Yes they are very specific.  I have not checked but I would think that they are constant between versions of the OWASP rule set versions but I don't know.  They have to be specific because that is how mod security knows how to modify the rule that was causing the issue.

For example this comes from the modsec_debug log:
`
[12/May/2017:21:29:47 --0300] [kimai-dev.local/sid#7f5ec9f4fe58][rid#7f5ebc6800a0][/extensions/ki_export/processor.php][1] Access denied with code 403 (phase 2). Pattern match "\\%((?!$|\\W)|[0-9a-fA-F]{2}|u[0-9a-fA-F]{4})" at ARGS:dateformat. [file "/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_20_protocol_violations.conf"] [line "465"] [id "950109"] [rev "2"] [msg "Multiple URL Encoding Detected"] [severity "WARNING"] [ver "OWASP_CRS/2.2.9"] [maturity "6"] [accuracy "8"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/EVASION"]
`
notice the

` [id: "950109"]`

That is how modsecurity tells you which rule is being triggered.

notice the:

`Pattern match "\\%((?!$|\\W)|[0-9a-fA-F]{2}|u[0-9a-fA-F]{4})" at ARGS:dateformat.`

That tells you that the ARGS:dateformat matched the rule.

The 
`SecRuleUpdateTargetById 950109 "!ARGS:dateformat"`

custom rule tell modsecurity to ignore the dateformat in the parameters sent to the server in rule 950109.

It has to be specific to make it work correctly but the custom rules I posted might not be the ones required for another version of the rules or for another version of kimai

Tim

**Comment by anchev** [comment]
Isn't it more correct to fix kimai so that it doesn't cause any protocol violations etc (what you show from the logs) instead of writing documentation how to circumvent the issue by configuring mod_security? My other sites which I develop locally never cause such issues.

**Comment by timlegge** [comment]
you make a valid point.  but the answer is slightly more complicated.  Its Yes, No, Maybe

So this morning I updated to the latest mod security core rule set from 

`git clone https://github.com/SpiderLabs/owasp-modsecurity-crs.git`

After grabbing the 

`wget https://raw.githubusercontent.com/SpiderLabs/ModSecurity/master/modsecurity.conf-recommended`

and configuring the rules and restarting I needed only the following exceptions:

```
SecRuleUpdateTargetById 930110 "!REQUEST_HEADERS:Cookie|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|!REQUEST_COOKIES:/^ki_active_tab_path_.*$/"
SecRuleUpdateTargetById 932150 "!ARGS:SAMLResponse"
```
The First one is required becaue of the way kimai keeps track of the last active tab:

`../extensions/ki_timesheets/init.php`

the embedded .. is picked up as a path traversal attack

So, the issues that an earlier version of the rules picked up were false positives that the current version does not look for anymore.

There is not much that can be done about the SAMLResponse because it has to do with the size of the parameter sent back from the SAML server.  Likely there is a better way to deal with it than the method I used.

Mod security attempts to protect a web application from malicious attacks and while a web application can have code changes to address things that modsecurity blocks it is not always possible.  Applications grow and evolve and so do attacks.  What is not an attack today may be one tomorrow and an updated modsecurity rule may block part of an application that worked fine up to now.

Tim
