### ISSUE TITLE
Error on customer login

### ISSUE THREAD

**Issue by Petruzzo79** [kimai/kimai#949]
When try to login as customer the server return 500

#### Steps to reproduce
try to login with custumer id and password set in customer field
#### Reproducable on demo.kimai.org? [yes|no]
yes
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
dev 1.2.1.1393 github develop
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
mod_fcgid: stderr: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Kimai_User::__construct() must be of the type array, null given, called in /kimai/includes/func.php on line 41 and defined in /kimai/libraries/Kimai/User.php:35, referer: http://XXX/kimai/
[fcgid:warn] mod_fcgid: stderr: Stack trace:, referer: http://XXX/kimai/
[fcgid:warn] mod_fcgid: stderr: #0 /kimai/includes/func.php(41): Kimai_User->__construct(NULL), referer: http://XXX/kimai/
[fcgid:warn] mod_fcgid: stderr: #1 /core/kimai.php(38): checkUser(), referer: http://XXX/kimai/
[fcgid:warn] mod_fcgid: stderr: #2 {main}, referer: http://XXX/kimai/
[fcgid:warn]mod_fcgid: stderr:   thrown in /kimai/libraries/Kimai/User.php on line 35, referer: http://XXX/kimai/

**Comment by timlegge** [comment]
The issue is due to a bug that the following patch will fix.  However, I have not used this functionality so I don't know whether the rest of the customer functions work or what exactly it is used for:

diff --git a/libraries/Kimai/Database/Mysql.php b/libraries/Kimai/Database/Mysql.php
index 09f53d3..5377850 100644
--- a/libraries/Kimai/Database/Mysql.php
+++ b/libraries/Kimai/Database/Mysql.php
@@ -2889,6 +2889,8 @@ class Kimai_Database_Mysql
 
         if (isset($this->kga['user'])) {
             return $this->kga['user'];
+        } else {
+            return $this->kga['customer'];
         }
 
         return null;
