### ISSUE TITLE
Tabs not loading

### ISSUE THREAD

**Issue by c3r63ru5** [kimai/kimai#977]
#### Expected behaviour
After login, all extensions are properly loaded.

#### Actual behaviour
None of the extensions are loading, the admin can login and sees no tabs at all.

#### Steps to reproduce
Fresh Ubuntu install with Apache and PHP, unzip Kimai 1.1.0 and change permissions, complete setup process and login as admin.

#### Reproducable on demo.kimai.org? [yes|no]
No

#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
1.1.0 (stable)

#### Relevant log entries from log file (debug tab or temporary/logfile.txt)
Neither Apache error log not Kimai log shows any error.

#### Comments
I checked and it seems the extensions are just not loaded, this is visible in Firebug when checking which stylesheets and includes are loaded (none)...

**Comment by timlegge** [comment]
Try clearing your cache or opening in a private mode of the browser.  I had a similar issue last week after moving between versions.

**Comment by c3r63ru5** [comment]
> Try clearing your cache or opening in a private mode of the browser
I tried clearing cache and also opening in a different browser, unfortunately this does not help.

**Comment by timlegge** [comment]
Is this a new install?  Check to ensure that the web server has read access to all the files.  Are you sure that there are no errors in the web server logs?  If its apache on linux run ls -lrt  in the apache logs directory  to determine which one was written to last.

**Comment by simonschaufi** [comment]
Which Ubuntu Version are you using? PHP Version? This is mostly not a kimai problem but your environment does not fit. I just setup kimai recently on a fresh Ubuntu 16 with PHP 7 and had no problems except this one (php-xml was missing): https://github.com/kimai/documentation/tree/master/installation#installation-on-ubuntu

**Comment by c3r63ru5** [comment]
Its a fresh install, installed multiple times on fresh docker php5 image, also tried with Docker Ubuntu 16.04 with Apache and PHP7 (also had to install php-xml). I'm using an external mysql db (which seems to work fine) and apache is behind haproxy.

Only difference I can see between this and other installs is haproxy but I don't understand why this should be related to the issue I'm seeing....

**Comment by simonschaufi** [comment]
I never heard about haproxy but I saw that it's a load balancer. Since kimai makes plenty of background ajax requests, this could be indeed the source of the problem.

**Comment by c3r63ru5** [comment]
I just tried without haproxy without any difference in behaviour, so it was not the proxy causing this. What could prevent kimai.php from loading the extensions? The only thing I can see is the open and closing comments for extension css and js but without any content, thats why the functions are not loaded...

**Comment by timlegge** [comment]
Are you runing modsecurity by any chance?  I imagine the extensions are not disabled like https://github.com/kimai/documentation/blob/master/developer/extensions.md but its worth a look.

I assume you did a chown -R www-data:www-data kimai

Can you look in the developer view (or better use a web proxy like Charles Web Proxy or the OWASP ZAP proxy to look at the response to the request.

Also, look in the apache access and error log as well as the kimai/temporary/logfile.txt.  Something must be showing an error  message

Tim

**Comment by c3r63ru5** [comment]
No modsecurity, this is a blank ubuntu+Apache2+PHP5, also tried with PHP7 just to see if that makes any difference. I did unzip and chown, also tried to chmod 777, just to see if its a permissions problem, I first thought Kimai.php could maybe not list the extensions-folder but thats not the case. The apache error log and Kimai log show no errors at all. The only thing that shows up are normal access in apache and the login with the admin user in the Kimai log.

I looked at the requests/responses in a proxy but the only difference between working (which I have on another server) and this fresh install is the response of kimai.php, the working version lists all extension scripts/stylesheets and the fresh install does not. The install script already does a good job checking dependencies and permissions, but that all goes fine without any errors...

**Comment by timlegge** [comment]
If it could not talk to the database you would not get the main page and an error would be presented in the browser.

Here are the pages I get when I login.  I am using SAML so I did not show the login.   The best I can offer is to login and then try some of them and see whether you get any errors.  It is possible one of the files has some corruption I suppose (did you download the zip again?) but that is unlikely because others would have the issue.

http://kimai.local/
http://kimai.local/core/floaters.php
http://kimai.local/core/kimai.php
http://kimai.local/extensions/ext_debug/css/styles.css.php
http://kimai.local/extensions/ext_debug/js/func.js
http://kimai.local/extensions/ext_debug/js/init.js
http://kimai.local/extensions/ki_adminpanel/css/advanced.css
http://kimai.local/extensions/ki_adminpanel/css/setup.css.php
http://kimai.local/extensions/ki_adminpanel/css/styles.css
http://kimai.local/extensions/ki_adminpanel/css/subtabs.css.php
http://kimai.local/extensions/ki_adminpanel/css/tables.css
http://kimai.local/extensions/ki_adminpanel/js/ap_func.js
http://kimai.local/extensions/ki_adminpanel/js/ap_init.js
http://kimai.local/extensions/ki_adminpanel/js/flotala.js
http://kimai.local/extensions/ki_budget/css/styles.css
http://kimai.local/extensions/ki_budget/init.php
http://kimai.local/extensions/ki_budget/js/budget_func.js
http://kimai.local/extensions/ki_budget/js/budget_init.js
http://kimai.local/extensions/ki_budget/processor.php
http://kimai.local/extensions/ki_expenses/css/setup.css.php
http://kimai.local/extensions/ki_expenses/css/styles.css
http://kimai.local/extensions/ki_expenses/css/tables.css.php
http://kimai.local/extensions/ki_expenses/js/exp_func.js
http://kimai.local/extensions/ki_expenses/js/exp_init.js
http://kimai.local/extensions/ki_export/css/optiontabs.css
http://kimai.local/extensions/ki_export/css/panel.css
http://kimai.local/extensions/ki_export/css/setup.css.php
http://kimai.local/extensions/ki_export/css/styles.css
http://kimai.local/extensions/ki_export/css/tables.css.php
http://kimai.local/extensions/ki_export/js/xp_func.js
http://kimai.local/extensions/ki_export/js/xp_init.js
http://kimai.local/extensions/ki_invoice/css/styles.css.php
http://kimai.local/extensions/ki_invoice/js/invoice_init.js
http://kimai.local/extensions/ki_timesheets/css/setup.css.php
http://kimai.local/extensions/ki_timesheets/css/styles.css
http://kimai.local/extensions/ki_timesheets/css/tables.css.php
http://kimai.local/extensions/ki_timesheets/js/ts_func.js
http://kimai.local/extensions/ki_timesheets/js/ts_init.js
http://kimai.local/index.php
http://kimai.local/js/init.js
http://kimai.local/js/main.js
http://kimai.local/libraries/jQuery/jqplot.pieRenderer.min.js
http://kimai.local/libraries/jQuery/jquery-1.9.1.min.js
http://kimai.local/libraries/jQuery/jquery-ui-1.10.2.min.js
http://kimai.local/libraries/jQuery/jquery-ui-timepicker/jquery.ui.timepicker.js
http://kimai.local/libraries/jQuery/jquery.form.min.js
http://kimai.local/libraries/jQuery/jquery.hoverIntent.minified.js
http://kimai.local/libraries/jQuery/jquery.jqplot.min.js
http://kimai.local/libraries/jQuery/jquery.newsticker.pack.js
http://kimai.local/libraries/jQuery/jquery.selectboxes.min.js
http://kimai.local/libraries/jQuery/js.cookie-2.1.0.min.js
http://kimai.local/libraries/phpjs/strftime.min.js
http://kimai.local/skins/standard/buzzer.css
http://kimai.local/skins/standard/datepicker.css
http://kimai.local/skins/standard/dropdowns.css
http://kimai.local/skins/standard/floater.css
http://kimai.local/skins/standard/jquery.autocomplete.css
http://kimai.local/skins/standard/jquery.jqplot.css
http://kimai.local/skins/standard/lists.css
http://kimai.local/skins/standard/menu.css
http://kimai.local/skins/standard/selector.css
http://kimai.local/skins/standard/setup.css
http://kimai.local/skins/standard/stopwatch.css
http://kimai.local/skins/standard/styles.css
http://kimai.local/skins/standard/tables.css
http://kimai.local/skins/standard/timePicker.css
http://kimai.local/skins/standard/timeframe.css
http://kimai.local/skins/standard/toolsmenu.css

**Comment by timlegge** [comment]
new Ubuntu 17.04 installed with ssh-server only during the install

Here are the commands I used to get a working kimai application.  I deleted the lines where I forgot to type sudo first

    1  sudo apt-get install apache2
    2  sudo apt-get install php-xml
    3  wget https://github.com/kimai/kimai/releases/download/1.1.0/kimai_1.1.0.zip
    5  sudo apt-get install unzip 
    8  sudo mkdir kimai
    9  cd kimai/
   14  sudo unzip ../kimai_1.1.0.zip 
   15  cd /var/www/
   17  sudo mv /home/me/kimai ./
   19  sudo chown www-data:www-data kimai
   20  sudo apt-get install mysql-server
   21  ifconfig 
   23  sudo service networking restart
here I had changed my VM nic to be bridged instead of NAT
   24  ifconfig 
   26  sudo vim /etc/apache2/sites-available/000-default.conf 
`modified: DocumentRoot to be /var/www/kimai`
   28  sudo /etc/init.d/apache2 restart
   35  sudo apt-get install libapache2-mod-php
   36  sudo /etc/init.d/apache2 restart
   39  sudo apt-get install php-mysql
   42  sudo phpenmod mysqli
   43  sudo /etc/init.d/apache2 restart
   45  sudo chown -R www-data:www-data kimai

**Comment by c3r63ru5** [comment]
OK, this is exactly what I did multiple times, with one difference: I always used an external database. I now tried using a local mysql install and all works as expected.

The database I'm using is a mariadb cluster... not sure why this would cause any problems.

**Comment by simonschaufi** [comment]
Maybe it does not work properly with the Ajax requests in the background. since I don't have a cloud available, i can't test it
