### ISSUE TITLE
Hosting requirements

### ISSUE THREAD

**Issue by mmoehring** [kimai/kimai#986]
Regarding hosting of kimai, aside from the requirements mentioned on the homepage (PHP 5.4 and access to a MySQL database) are there any other requirements which need attention when looking for shared hosting for kimai?
(e.g. thing like in this thread https://forum.kimai.org/index.php?topic=3782.0)

Are there any statistics about the installation size and the expected size growth? (e.g. per user per year)?

**Comment by simonschaufi** [comment]
Kimai has very basic requirements. Did you also have a look here? http://www.kimai.org/documentation/installation/index.html
If it does not work on your hoster, please let us know!

No, we don't have any statistics but since we only deal with mysql data, it depends on how many entries you generate per day per user. Invoice generation is currently in development, that will grow much more of course as the files will then be stored on the server.
Hope this helps.

**Comment by timlegge** [comment]
As Simon says growth depends on usage.  If this helps, we have 100 users and started April 1.  There are 1345 timesheet records.  Total disk usage for the database is 248K and the backup using automysqlbackup is a 36K gzip tar file.  Based on that I would say less than ten megs of growth per year for our usage.

I have not looked at how many of those users actually log data regularly.  We use it for internal project costing not billing so it probably on the low side compared to people who need to bill based on time.
